### ISSUE TITLE
Well-founded recursion: simp can introduce additional, unsolvable recursive calls

### ISSUE THREAD

**Issue by kendfrey** [leanprover/lean4#2893] opened 2023-11-16 20:32 UTC
### Description

It appears the well-founded recursion checker is generating spurious goals in which the decreasing proof added with `have` is missing, causing the check to fail.

### Context

Some code used in the sample, including a couple of sorried mathlib lemmas to remove the dependency:

```lean
-- Same as List.map but passes a proof that the element is in the list to the mapping function
@[simp] def List.mapMem {α β} : (l : List α) → ((a : α) → a ∈ l → β) → List β
| [], _ => []
| x :: xs, f => f x (.head _) :: mapMem xs (λ a h => f a (.tail _ h))

@[simp] theorem List.mapMem_eq_nil {α β} : (l : List α) → (f : (a : α) → a ∈ l → β) → mapMem l f = [] ↔ l = []
| [], _ => by simp
| x :: xs, f => by simp

-- Maximum of a nonempty list
def List.max1 {α} [Max α] : (l : List α) → l ≠ [] → α
| [x], _ => x
| x :: y :: xs, _ => max x (max1 (y :: xs) (by simp))

@[simp] theorem List.range_eq_nil {n : Nat} : range n = [] ↔ n = 0 := sorry -- Borrowed from mathlib

@[simp] theorem List.mem_range {m n : Nat} : m ∈ range n ↔ m < n := sorry -- Borrowed from mathlib
```

#### Part 1
```lean
def optimalScore (a : Nat) : Nat :=
  if a_ne_zero : a = 0 then
    0
  else
    let f : (b : Nat) → b ∈ List.range a → Nat :=
      λ b b_mem_range_a =>
        have h : b < a := List.mem_range.mp b_mem_range_a
        optimalScore b + 1
    ((List.range a).mapMem f).max1 (by simp [a_ne_zero])
termination_by optimalScore a => a
```

**Expected behavior:** No errors

**Actual behavior:** `optimalScore b` is highlighted with the following error:
```
failed to prove termination, possible solutions:
  - Use `have`-expressions to prove the remaining goals
  - Use `termination_by` to specify a different well-founded relation
  - Use `decreasing_by` to specify your own tactic for discharging this kind of goal

a: Nat
a_ne_zero: ¬a = 0
b: Nat
b_mem_range_a: b ∈ List.range a
⊢ b < a
```

Note that `h` is missing from the context.

#### Part 2 (Diagnostic)
Add `decreasing_by show b < a; exact _`. Now the infoview reports the following goal state:
```
a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
h : b < a
⊢ b < a

a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
⊢ b < a

a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
⊢ b < a

a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
⊢ b < a

a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
⊢ b < a

a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
⊢ b < a

a : Nat
a_ne_zero : ¬a = 0
b : Nat
b_mem_range_a : b ∈ List.range a
⊢ b < a
```

The "correct" goal appears once, and then there are six copies of the same goal but with `h` missing.

#### Part 3 (Workaround)
Change it to `decreasing_by show b < a; exact List.mem_range.mp b_mem_range_a`. Now compilation succeeds with no errors.

### Versions

4.2.0-rc4
Windows 10

### Additional Information

Possibly related to #1694

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment] 2023-11-16 20:39
Thanks for the report and the already pretty good example. I wonder if it can be minimized even more, maybe that would give some insight why there are 6 goals there.

**Comment by kendfrey** [comment] 2023-11-16 20:45
FWIW, the original scenario this was simplified from had a total of only 6 goals (1 good, 5 dud)

**Comment by nomeata** [comment] 2023-11-17 09:21
I think could narrow it down to this line:

https://github.com/leanprover/lean4/blob/5d1d493635c7b5ffa9895ab543591e10adb3e41f/src/Lean/Elab/PreDefinition/WF/Fix.lean#L189

On a branch where the goals are not handled individually, but left in as unsolved MVars I could use
```
      dbg_trace "{(← getMVars val).size}"
```
to see how many there are. Here `val` has the expected number of goals, but after
```
      let val ← mkLambdaFVars #[x, F] val
```
I see extra goals.

Could `mkLambdaFVars` somehow mess with that? (But maybe I am barking up the wrong tree here)

**Comment by nomeata** [comment] 2023-11-17 09:38
Yes, wrong tree. The issue is with `(by simp [a_ne_zero])` in
```
((List.range a).mapMem f).max1 (by simp [a_ne_zero])
```
if I replace that with `by sorry` we only get one goal.

The problem is probably the following: The type and terms of that theorem involve `(List.range a).mapMem f` somehow, and maybe `simp` beta-reduces the `let` and then also the (seemingly unused) `let h` there.

It works if you use simpler tactics:
```
(by rw [ne_eq, List.mapMem_eq_nil, List.range_eq_nil]; exact a_ne_zero)
```

**Comment by nomeata** [comment] 2023-11-17 09:40
Marking this as low priority. In a way, all components work as advertised, and the interplay causes an unfortunate outcome, and there are work-arounds. (You could also abstract a helper lemma, proved with `simp`, to avoid inlining `f`, I assume.)

**Closed** 2024-08-22 14:07 UTC
Labels: bug, low priority, P-low
