### ISSUE TITLE
Segmentation fault with custom GetElem instance

### ISSUE THREAD

**Issue by jakobrs** [leanprover/lean4#4745] opened 2024-07-15 12:48 UTC
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
      I couldn't find anything when searching for "segmentation fault", "sigsegv" or "getelem"
      There is another recent bug report about a segmentation fault (#4703), but the stack trace is completely different.
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

I tried implementing `GetElem` for a subtype of `List Int` where the length of the list is given in the type, and found that the Lean interpreter segfaults if a normal out-of-bounds access is attempted.

The segmentation fault only occurs if an out-of-bounds access is attempted using either normal `vec[idx]` or `vec[idx]'(by simp)` syntax (`vec[idx]?` and `vec[idx]!` work fine), and it only occurs in `#eval` (see the code example)

### Context

No relevant context

### Steps to Reproduce

Small example that demonstates the issue ([link](https://live.lean-lang.org/#code=def%20Vector%20(d%20%3A%20Nat)%20%3A%20Type%20%3A%3D%20%7B%20v%20%3A%20List%20Int%20%2F%2F%20v.length%20%3D%20d%20%7D%0A%0A%40%5Bsimp%5D%0Atheorem%20Vector.val_length%20%3A%20forall%20%7Bd%20%3A%20Nat%7D%20(v%20%3A%20Vector%20d)%2C%20v.val.length%20%3D%20d%0A%20%20%7C%20_%2C%20%E2%9F%A8_%2C%20h%E2%9F%A9%20%3D%3E%20h%0A%0Adef%20Vector.get%20(v%20%3A%20Vector%20r)%20(idx%20%3A%20Fin%20r)%20%3A%20Int%20%3A%3D%0A%20%20have%20%3A%20r%20%3D%20v.val.length%20%3A%3D%20by%20simp%0A%20%20v.val.get%20(this%20%E2%96%B8%20idx)%0A%0Adef%20Vector.getElem%20(v%20%3A%20Vector%20d)%20(i%20%3A%20Nat)%20(h%20%3A%20i%20%3C%20d)%20%3A%20Int%20%3A%3D%0A%20%20v.get%20%E2%9F%A8i%2C%20h%E2%9F%A9%0A%0Ainstance%20%3A%20GetElem%20(Vector%20d)%20Nat%20Int%20(fun%20_%20i%20%3D%3E%20i%20%3C%20d)%20where%0A%20%20getElem%20%3A%3D%20Vector.getElem%0A%0Adef%20q%20%3A%20Vector%202%20%3A%3D%20%E2%9F%A8%5B1%2C%202%5D%2C%20by%20simp%E2%9F%A9%0A%0A--%20These%20should%20crash%0A--%20%23eval%20q%5B2%5D%0A--%20%23eval%20q%5B2%5D'(by%20simp)%0A%0A--%20These%20should%20not%20crash%0A%23eval%20q%5B2%5D!%0A%23eval%20q%5B2%5D%3F%0A%0A--%20This%20should%20not%20compile%0Adef%20main%20%3A%20IO%20Unit%20%3A%3D%20do%0A%20%20IO.println%20(q%5B2%5D'(by%20simp))%0A%0A--%20This%20crashes%20locally%0A--%20%23eval%20main%0A))

```lean
def Vector (d : Nat) : Type := { v : List Int // v.length = d }

@[simp]
theorem Vector.val_length : forall {d : Nat} (v : Vector d), v.val.length = d
  | _, ⟨_, h⟩ => h

def Vector.get (v : Vector r) (idx : Fin r) : Int :=
  have : r = v.val.length := by simp
  v.val.get (this ▸ idx)

def Vector.getElem (v : Vector d) (i : Nat) (h : i < d) : Int :=
  v.get ⟨i, h⟩

instance : GetElem (Vector d) Nat Int (fun _ i => i < d) where
  getElem := Vector.getElem

def q : Vector 2 := ⟨[1, 2], by simp⟩

-- These should crash
#eval q[2]
#eval q[2]'(by simp)

-- These should not crash
#eval q[2]!
#eval q[2]?

-- This should not compile
def main : IO Unit := do
  IO.println (q[2]'(by simp))

-- This crashes locally
#eval main
```

**Expected behavior:** Some kind of compile error, like if I was trying to index an ordinary list

**Actual behavior:** Segmentation fault

Note: when writing `q[2]'(by simp)` in VSCode in a normal definition, the goal gets simplified to `False` (as expected, and without segfaulting)

### Versions

4.9.0, on Arch Linux (latest version as of 2024-07-15) (also reproduced on https://live.lean-lang.org)

### Additional Information

Looks to me like it tries to actually read the third element of the two-element list (from `l_List_get__rarg`)
```
#0  0x00007c6f1f6af5c3 in l_List_get___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#1  0x00007c6f1f6af6bf in l_List_get___rarg___boxed () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#2  0x00007c6f22fda1f4 in lean::ir::interpreter::call(lean::name const&, lean::array_ref<lean::object_ref> const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#3  0x00007c6f22fd8450 in lean::ir::interpreter::eval_body(lean::object_ref const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#4  0x00007c6f22fd5f51 in lean::ir::interpreter::load(lean::name const&, lean::ir::type) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#5  0x00007c6f22fd8450 in lean::ir::interpreter::eval_body(lean::object_ref const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#6  0x00007c6f22fda532 in lean::ir::interpreter::call(lean::name const&, lean::array_ref<lean::object_ref> const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#7  0x00007c6f22fd8450 in lean::ir::interpreter::eval_body(lean::object_ref const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#8  0x00007c6f22fdc073 in lean::ir::interpreter::stub_m(lean_object**) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#9  0x00007c6f22fdbcf7 in lean::ir::interpreter::stub_m_aux(lean_object**) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#10 0x00007c6f22fdb89f in lean::ir::interpreter::stub_4_aux(lean_object*, lean_object*, lean_object*, lean_object*) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#11 0x00007c6f22fee257 in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#12 0x00007c6f22fd9980 in lean::ir::interpreter::eval_expr(lean::object_ref const&, lean::ir::type) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#13 0x00007c6f22fd8450 in lean::ir::interpreter::eval_body(lean::object_ref const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#14 0x00007c6f22fdc073 in lean::ir::interpreter::stub_m(lean_object**) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#15 0x00007c6f22fdbcf7 in lean::ir::interpreter::stub_m_aux(lean_object**) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#16 0x00007c6f22fdb8d4 in lean::ir::interpreter::stub_5_aux(lean_object*, lean_object*, lean_object*, lean_object*, lean_object*) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#17 0x00007c6f22fedf51 in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#18 0x00007c6f1f72578e in l_IO_withStderr___at_Lean_runEval___spec__4 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#19 0x00007c6f22fedf1d in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#20 0x00007c6f1f72508e in l_IO_withStdout___at_Lean_runEval___spec__2 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#21 0x00007c6f22fedf1d in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#22 0x00007c6f1f72540e in l_IO_withStdin___at_Lean_runEval___spec__3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#23 0x00007c6f1f725c02 in l_IO_FS_withIsolatedStreams___at_Lean_runEval___spec__1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#24 0x00007c6f22fda1f4 in lean::ir::interpreter::call(lean::name const&, lean::array_ref<lean::object_ref> const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#25 0x00007c6f22fd8450 in lean::ir::interpreter::eval_body(lean::object_ref const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#26 0x00007c6f22fda532 in lean::ir::interpreter::call(lean::name const&, lean::array_ref<lean::object_ref> const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#27 0x00007c6f22fd8450 in lean::ir::interpreter::eval_body(lean::object_ref const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#28 0x00007c6f22fdc073 in lean::ir::interpreter::stub_m(lean_object**) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#29 0x00007c6f22fd4e61 in lean_object* lean::ir::interpreter::with_interpreter<lean_object*>(lean::environment const&, lean::options const&, lean::name const&, std::__1::function<lean_object* (lean::ir::interpreter&)> const&) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#30 0x00007c6f22fdbcf7 in lean::ir::interpreter::stub_m_aux(lean_object**) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#31 0x00007c6f22fdb89f in lean::ir::interpreter::stub_4_aux(lean_object*, lean_object*, lean_object*, lean_object*) () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#32 0x00007c6f22fedf35 in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#33 0x00007c6f203d1fc2 in l_Lean_Elab_Command_elabEvalUnsafe___lambda__5 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#34 0x00007c6f22ff32d4 in lean_apply_7 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#35 0x00007c6f20a224ea in l___private_Lean_Elab_InfoTree_Main_0__Lean_Elab_withSavedPartialInfoContext___at_Lean_Elab_Term_withDeclName___spec__2___rarg___lambda__1 ()
   from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#36 0x00007c6f20a23f56 in l___private_Lean_Elab_InfoTree_Main_0__Lean_Elab_withSavedPartialInfoContext___at_Lean_Elab_Term_withDeclName___spec__2___rarg ()
   from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#37 0x00007c6f20a24782 in l_Lean_Elab_Term_withDeclName___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#38 0x00007c6f203d4a9e in l_Lean_Elab_Command_elabEvalUnsafe___lambda__6___boxed () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#39 0x00007c6f22ff32d4 in lean_apply_7 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#40 0x00007c6f20ab6122 in l_Lean_Elab_Term_withoutAutoBoundImplicit___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#41 0x00007c6f1fc98229 in l_Lean_Elab_Command_runTermElabM___rarg___lambda__1___boxed () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#42 0x00007c6f22ff4b10 in lean_apply_9 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#43 0x00007c6f20ac878b in l_Lean_Elab_Term_addAutoBoundImplicits_x27___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#44 0x00007c6f1fc97d17 in l_Lean_Elab_Command_runTermElabM___rarg___lambda__2 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#45 0x00007c6f1fc98422 in l_Lean_Elab_Command_runTermElabM___rarg___lambda__2___boxed () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#46 0x00007c6f22ff4175 in lean_apply_8 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#47 0x00007c6f22ff3281 in lean_apply_7 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#48 0x00007c6f20ae5d11 in l_Lean_Elab_Term_universeConstraintsCheckpoint___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#49 0x00007c6f1fa16ff6 in l_Lean_Elab_Term_elabBindersEx___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#50 0x00007c6f22ff34e7 in lean_apply_7 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#51 0x00007c6f20ab3b24 in l_Lean_Elab_Term_withAutoBoundImplicit_loop___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#52 0x00007c6f20ab5e97 in l_Lean_Elab_Term_withAutoBoundImplicit___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#53 0x00007c6f22ff3237 in lean_apply_7 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#54 0x00007c6f1fc9381a in l___private_Lean_Elab_InfoTree_Main_0__Lean_Elab_withSavedPartialInfoContext___at_Lean_Elab_Command_liftTermElabM___spec__2___rarg___lambda__1 ()
   from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#55 0x00007c6f1fc95286 in l___private_Lean_Elab_InfoTree_Main_0__Lean_Elab_withSavedPartialInfoContext___at_Lean_Elab_Command_liftTermElabM___spec__2___rarg ()
   from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#56 0x00007c6f1fc9599f in l_Lean_Elab_Command_liftTermElabM___rarg___lambda__1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#57 0x00007c6f22ff3237 in lean_apply_7 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#58 0x00007c6f20ad85f6 in l_Lean_Elab_Term_TermElabM_run___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#59 0x00007c6f22ff1950 in lean_apply_5 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#60 0x00007c6f20f178b8 in l_Lean_Meta_MetaM_run___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#61 0x00007c6f22fefe73 in lean_apply_3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#62 0x00007c6f1fc440de in l___private_Lean_Elab_Command_0__Lean_Elab_Command_runCore___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#63 0x00007c6f1fc962ec in l_Lean_Elab_Command_liftTermElabM___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#64 0x00007c6f203d3476 in l_Lean_Elab_Command_elabEvalUnsafe () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#65 0x00007c6f22fefe3b in lean_apply_3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#66 0x00007c6f1fc64eb9 in l_Lean_Elab_withInfoTreeContext___at___private_Lean_Elab_Command_0__Lean_Elab_Command_elabCommandUsing___spec__2 ()
   from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#67 0x00007c6f22fefe55 in lean_apply_3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#68 0x00007c6f1fc670fb in l___private_Lean_Elab_Command_0__Lean_Elab_Command_elabCommandUsing () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#69 0x00007c6f22fefe73 in lean_apply_3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#70 0x00007c6f1fc5bf1d in l_Lean_withTraceNode___at_Lean_Elab_Command_runLinters___spec__10 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#71 0x00007c6f22fefeb4 in lean_apply_3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#72 0x00007c6f22fefe55 in lean_apply_3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#73 0x00007c6f1fc6d192 in l_Lean_Elab_withLogging___at_Lean_Elab_Command_elabCommand___spec__2 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#74 0x00007c6f1fc852cf in l_Lean_Elab_Command_elabCommandTopLevel___lambda__2 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#75 0x00007c6f22fedf35 in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#76 0x00007c6f2253f33e in l_Lean_profileitIOUnsafe___rarg___lambda__1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#77 0x00007c6f2253f53f in l_Lean_profileitIOUnsafe___rarg___lambda__1___boxed () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#78 0x00007c6f22fedf09 in lean_apply_1 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#79 0x00007c6f22f34a64 in lean_profileit () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#80 0x00007c6f2253f460 in l_Lean_profileitIOUnsafe___rarg () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#81 0x00007c6f1fc88951 in l_Lean_Elab_Command_elabCommandTopLevel () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#82 0x00007c6f1f940db3 in l_Lean_Elab_Frontend_elabCommandAtFrontend () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#83 0x00007c6f1f94447b in l_Lean_Elab_Frontend_processCommand () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#84 0x00007c6f1f944fc0 in l_Lean_Elab_Frontend_processCommands () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#85 0x00007c6f1f94539a in l_Lean_Elab_IO_processCommands () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#86 0x00007c6f1f949088 in l_Lean_Elab_runFrontend___lambda__3 () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#87 0x00007c6f1f94a40a in lean_run_frontend () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#88 0x00007c6f22ece2bf in lean::run_new_frontend(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, lean::options const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, lean::name const&, unsigned int, lean::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > const&, unsigned char)
    () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#89 0x00007c6f22ed0d1e in lean_main () from /home/user/.elan/toolchains/stable/bin/../lib/lean/libleanshared.so
#90 0x00007c6f1e54ec88 in __libc_start_call_main (main=main@entry=0x57c2f483e840 <main>, argc=argc@entry=2, argv=argv@entry=0x7fff32f72da8) at ../sysdeps/nptl/libc_start_call_main.h:58
#91 0x00007c6f1e54ed4c in __libc_start_main_impl (main=0x57c2f483e840 <main>, argc=2, argv=0x7fff32f72da8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff32f72d98)
    at ../csu/libc-start.c:360
#92 0x000057c2f483e775 in _start ()
```

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment] 2024-07-19 08:55
Looks like a duplicate of #1697

**Closed by Kha** 2024-07-19 08:55 UTC
Labels: bug
