### ISSUE TITLE
Incorrect hover in infoview for lambda binders

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#2737] opened 2023-10-23 05:13 UTC
Enter the following:
```lean
#check fun _x : Nat => ()
```
A message appears in the infoview:
```lean
fun _x => () : Nat → Unit
```
Hover on the `_x` here, and you are presented with a tooltip containing:
```lean
fun _x => () : Nat → Unit
```
hovering on the `_x` here pops up another similar tooltip, and so on.

It should instead show a hover saying:
```lean
_x : Nat
```
This is especially important because function binders by default do not show their types (unless you use `set_option pp.funBinderTypes true`), so this foils the natural method of seeing what the type is (although you can deduce that the type is `Nat` because it says `Nat → Unit` on the right).

**Comment by Vtec234** [comment] 2023-10-23 16:17
Possibly duplicate of #1618?

**Closed** 2024-03-29 04:32 UTC
Labels: bug, server
