### ISSUE TITLE
Type class synthesis failure when specifying instance explicitly

### ISSUE THREAD

**Issue by SReichelt** [leanprover/lean4#952] opened 2022-01-14 23:58 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

When specifying an explicit type class instance argument, often that argument is not propagated the same way that an argument for a normal parameter would be, leading to errors at innocent-looking places as shown below.

### Steps to Reproduce

```lean
class A where
β : Sort v

structure B [a : A] where
b : a.β

def aDef : A := ⟨True⟩

-- These all fail with "failed to synthesize instance `A`" even though it is
-- given by `a` and should not be synthesized in the first place.
def fail₁ : B (a := aDef) := ⟨trivial⟩
def fail₂ : B (a := aDef) := { b := trivial }
def fail₃ : B (a := aDef) := ⟨sorry⟩

def workaround : B (a := aDef) := B.mk (a := aDef) trivial
```

**Expected behavior:** All `def`s should typecheck, as they do if `[a : A]` is replaced by `(a : A)`.

**Actual behavior:** The indicated definitions fail to type-check with "failed to synthesize instance `A`". Apparently, the `⟨⟩` and `{}` perform unnecessary type class synthesis for arguments that are already determined by the expected type.

**Reproduces how often:** always

### Versions

Lean (version 4.0.0-nightly-2022-01-14, commit 6d235586f055, Release)
Ubuntu 20.04.3 LTS

### Additional Information

This unnecessary synthesis can also cause other problems; I sometimes have to increase `synthInstance.maxHeartbeats` to avoid timeouts at `⟨⟩` or `{}`.

**Comment by leodemoura** [comment] 2022-01-17 17:09
This is the intended behavior in Lean 4. For any argument of the form `[...]` a type class resolution problem is created even if the argument value can be inferred by typing constraints. 

@Kha @gebner Any thoughts?

**Comment by SReichelt** [comment] 2022-01-17 23:13
That makes sense to me in principle, in fact I wouldn't necessarily expect e.g. `def b : B (a := aDef) := B.mk trivial` to work. However, with `⟨⟩` and `{}` because there isn't even a way to explicitly give the wrongly synthesized argument (that I'm aware of). Thinking about it a bit more, I'd say that I expect `⟨x⟩` to be a shorthand for `@A.mk a b c ... x`, where `@A a b c ...` is the expected type. Do you think it be possible to change `⟨⟩` and `{}` in a way that makes this true?

**Comment by leodemoura** [comment] 2022-01-17 23:28
> That makes sense to me in principle, in fact I wouldn't necessarily expect e.g. def b : B (a := aDef) := B.mk trivial to work. However, with ⟨⟩ and {} the situation is different because there isn't even a way to explicitly give the wrongly synthesized argument (that I'm aware of). 

You can define a local instance.
```lean
def fail₁ : B (a := aDef) := let inst : A := aDef; ⟨trivial⟩
def fail₂ : B (a := aDef) := let inst : A := aDef; { b := trivial }
def fail₃ : B (a := aDef) := let inst : A := aDef; { b := trivial }
```

**Comment by leodemoura** [comment] 2022-01-17 23:31
> Thinking about it a bit more, I'd say that I expect ⟨x⟩ to be a shorthand for @A.mk a b c ... x, where @A a b c ... is the expected type. Do you think it would be possible to change ⟨⟩ and {} in a way that makes this true?

This can be implemented, but I am not sure whether this feature will generate even more confusion or not.
It is nice for us to claim that any `[ ... ]` parameter must be instantiated using TC resolution.

**Comment by Kha** [comment] 2022-01-18 08:51
Apart from violating the nice invariant, a major concern here would be elaboration instability, no? Different elaboration orders could lead to different inferred instances. Even if it does sound very enticing to shortcut here and in similar cases for performance.

**Comment by gebner** [comment] 2022-01-18 10:17
Yes, this is a known issue, also in Lean 3.  People typically run into it with the `Quotient` type, where all the core definitions require a `Setoid` type-class instance but you don't want to add global `Setoid` instances (because they're never canonical).  One solution is to write custom definitions where the `Setoid` is an implicit argument (i.e., `{s : Setoid α}` instead of `[Setoid α]`; see e.g. [`quotient.mk'`](https://leanprover-community.github.io/mathlib_docs/data/quot.html#quotient.mk%27) in mathlib).  Or just avoid `Quotient` entirely and use `Quot` instead.

In my eyes, the Lean behavior is correct and `Quotient`/`B` is bad library design.  If you can't declare canonical `Setoid`/`A` instances, then that parameter should be explicit/implicit and not instance-implicit.  Having multiple non-defeq instances is almost always a recipe for disaster.

> Apart from violating the nice invariant, a major concern here would be elaboration instability, no? Different elaboration orders could lead to different inferred instances. Even if it does sound very enticing to shortcut here and in similar cases for performance.

All the inferred instances here are filled in by unification, so in particular they're all defeq.  If elaboration succeeds, the inferred instance should be unique.  What can happen though is that the order of TC synthesis / unification might be switched, and unification>>TC works, but TC>>unification fails.  This shouldn't be an issue though as long as diamonds are avoided.

**Comment by SReichelt** [comment] 2022-01-18 13:16
> You can define a local instance.

Thank you for this hint, that is definitely a solution I can live with.

> This can be implemented, but I am not sure whether this feature will generate even more confusion or not.
> It is nice for us to claim that any `[ ... ]` parameter must be instantiated using TC resolution.

But `{}` and `⟨⟩` don't really have any parameters, do they? `B.mk` does, but I personally wouldn't consider those parameters as parameters of `{}` and `⟨⟩`.
Regarding confusion, I can only speak for myself, of course. Up to now, I had always thought of `{}` and `⟨⟩` as "construct whatever type is expected here", not "invoke `<type>.mk` with implicit parameters". That's why I was surprised when it failed with an error message about type class synthesis.

I'm wondering whether there are actually any cases that are currently valid but would become invalid with my suggestion. The only case I could think of is a coercion between two different specializations of the same type. But I haven't been able to construct an example; when I tried, it always failed earlier with "synthesized type class instance is not definitionally equal to expression inferred by typing rules". So it seems that the change wouldn't actually change any existing behavior, but only cause more cases to type-check successfully.

> Apart from violating the nice invariant, a major concern here would be elaboration instability, no? Different elaboration orders could lead to different inferred instances.

Aside from what I wrote in my previous paragraph, don't `{}` and `⟨⟩` already completely depend on elaboration because they only work if the expected type is known?

> Yes, this is a known issue, also in Lean 3. People typically run into it with the `Quotient` type, where all the core definitions require a `Setoid` type-class instance but you don't want to add global `Setoid` instances (because they're never canonical).

(FWIW, in my case I have `Category` and `Groupoid` type classes, where `Groupoid` inherits from `Category` but the isomorphisms of a `Category` also form a `Groupoid` on the same type (which is thus also a `Category` but a different one).)

**Comment by Kha** [comment] 2022-01-18 15:09
> don't `{}` and `⟨⟩` already completely depend on elaboration because they only work if the expected type is known?

Sure, but that in itself doesn't affect confluence. Lean will suspend their elaboration until the expected type is known. If you only consider confluence of successful elaboration though, you are right in that the existing defeq check on TC binders seems to enforce it.

**Comment by leodemoura** [comment] 2022-01-20 16:34
@Kha @gebner @SReichelt I am planning to close this issue since Lean is behaving as expected.
The commit above is for the `Quotient` issue that @gebner raised above.

**Closed** 2022-01-26 14:36 UTC
