### ISSUE TITLE
RFC/Bug : `noConfusion` generator gets confused when the type of an inductive isn't syntactically well-formed

### ISSUE THREAD

**Issue by arthur-adjedj** [leanprover/lean4#2500] opened 2023-08-31 20:35 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Upon trying to generate `noConfusion` lemmas on some inductive types for which the type is not syntactically a telescope, but definitionally is, the generator throws an error. 

### Steps to Reproduce

```lean
def Family := Type → Type

inductive Bad : Family
/-(kernel) error in 'noConfusion' generation, 'Bad' inductive datatype declaration is corrupted-/
```

**Expected behavior:** Elaborates with no issue.

**Actual behavior:** `noConfusion` generates an error stating that the datatype is corrupted.

**Reproduces how often:** 100%

### Versions

Lean 4.0.0-rc4

### Additional Information

The issue comes from the fact that the telescope call doesn't reduce [here](https://github.com/leanprover/lean4/blob/fec3575aaf6e41fb8c739e0e87280c0cba8f9c96/src/library/constructions/no_confusion.cpp#L42) because the environment isn't given to the function. Simply changing `to_telescope(lctx,...)` to `to_telescope(env,lctx,...)` solves the issue.

- User Experience: How does this feature improve the user experience?
   This allows user to give more relevant naming to the type of their inductive families

- Beneficiaries: Which Lean users and projects do benefit most from this feature/change?
  A few people have encountered that issue, it's nothing more than a small quality of life feature.

- Community Feedback: Have you sought feedback or insights from other Lean users?
  [This](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/inductive.20datatype.20declaration.20is.20corrupted/near/388380132) (short) Zulip thread leads me to believe this is a bug and not an intended missing feature, as suggested by @digama0 

- Maintainability: Will this change streamline code maintenance or simplify its structure?
  This wouldn't add any more burden to maintainability, and is a simple one-line fix to a small issue.

**Comment by semorrison** [comment] 2023-09-01 01:06
As @digama0 [said on zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/inductive.20datatype.20declaration.20is.20corrupted/near/388410663), it's not clear here whether the right solution is to be more restrictive (i.e. not allow this inductive in the first place) or to "fix" the `noConfusion` generator.

I think to proceed with the proposed solution (keeping in mind that increasing permissiveness around inductive types is inherently dangerous, *even if* there's every reason to believe this one might be safe) there would need to be a much clearer case that this is actually needed by users. What is the use case for the inductive types that this affects? Why hasn't this previously been a concern? etc. Without that, I suspect that there isn't available bandwidth for such changes.

**Comment by digama0** [comment] 2023-09-01 01:09
There were actually some mathlib inductives that had to be changed when this got tightened up. For example I think the topology generated by a collection of sets was once an inductive predicate with the type `Set (Set A)`, but it was changed to a definition which wraps an inductive of type `Set A -> Prop` when lean started rejecting this.

**Comment by arthur-adjedj** [comment] 2023-09-01 01:12
`Set A` is a good example of a use-case for this. Any other pattern of type families could be used as well, allowing the code to be more explicit as to how one should interpret such inductive type.

**Comment by arthur-adjedj** [comment] 2023-09-01 01:16
If it is ruled out that this shouldn't be extended, I believe that, if anything, making the error message clearer should be a good improvement.

**Comment by digama0** [comment] 2023-09-01 01:47
Apparently my memory is faulty, as all the examples I can find of this pattern were not actually defined as sets:
* `{add_monoid, monoid, add_group, group}.in_closure`, `measurable_space.generate_measurable`, `dynkin_system.generate_has`, `topological_space.generate_open`, `filter.generate_sets`, `filter.countable_generate_sets`, `is_poly` have all been inductive propositions from birth
* `chain_closure` was [changed](https://github.com/leanprover-community/mathlib/blame/13e08bf3458cc4b46273fabd087f28a50b680007/src/order/zorn.lean#L186C11-L186C24) from `set (set α)` to `set α → Prop` but for independent reasons (defeq abuse)

**Comment by arthur-adjedj** [comment] 2023-09-01 07:44
I see the fact that the feature is already working and used on `Prop`-types as an argument towards this fix. The system already works when using the feature. Furthermore, despite the error popping when generating `noConfusion`, the inductive type still exists and is usable:
```lean
def Family := Type → Type

inductive Bad : Family --error

#check Bad --Bad : Family```

**Comment by b-mehta** [comment] 2023-10-11 16:43
I just hit this issue in practice - my mathlib example was something like
```
import Mathlib.Data.Set.Basic

variable {V : Type*}

inductive Thing (s : Set V) : Set V
| basic : ∀ x ∈ s, Thing s x
```
which works in mathlib3. As far as I can see, this is just a regression from Lean 3, since it's a well-defined inductive type which you can prove things about. It's also confusing from a beginner point of view, since the error seems to suggest something is invalid in the syntax, even though it can be fixed by adding some non-disjoint constructors.

**Comment by arthur-adjedj** [comment] 2023-10-12 09:45
The error happens here (despite the codomain being a `Set`) because `noConfusion` gets triggered on any inductive type which allows for large elimination, a criteria that applies to `Thing` here.
Knowing that this is a regression and that the issue has now been hit in practice, my belief is that this fix in `noConfusion` is justified.

**Comment by semorrison** [comment] 2023-10-13 06:24
Okay -- can you mark the associated PR as ready for review?

**Closed** 2023-10-14 06:18 UTC
