### ISSUE TITLE
guard_msgs and trailing space

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3571] opened 2024-03-02 19:52 UTC
Consider this code:
```
#guard_msgs in
run_meta
  logInfo "Foo \nbar\nbaz"
```
The code action will add
```
/--
info: Foo 
bar
baz
-/
```
but then saving this file with default VSCode settings removes the extra space, turn it into
```
/--
info: Foo
bar
baz
-/
```
and then `#guard_msgs` complains again.

Maybe code shouldn’t produce messages with final newlines, but some tools (in particular `addSuggestion`) may, so it would be nice to handle this gracefully.

Possible fixes:

 * `#guard_msgs` could strip trailing spaces
 * `#guard_msgs` could highlight trailing spaces, by replacing it with `_`, or some unicode symbol indicating a placeholder (`⎵`).

### Versions

4.7.0-nightly-2024-03-01

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment] 2024-03-02 20:40
@nomeata Agreed.
Here is another missing feature. The command `test_single.sh` which compares the produced output against the expected one uses the following trick:
```
function exec_capture {
    # mvar suffixes like in `?m.123` are deterministic but prone to change on minor changes, so strip them
    LEAN_BACKTRACE=0 "$@" 2>&1 | perl -pe 's/(\?(\w|_\w+))\.[0-9]+/\1/g' > "$f.produced.out"
}
``` 
It would be great to have the same feature at `#guard_msgs`

**Comment by nomeata** [comment] 2024-03-02 21:11
Although that's now “domain specific knowledge”, a fair bit different than “robust representation of text”.

(Part of me would prefer if we make the MVars names more stable. Using a fresh name generator per command maybe, or normalizing then at some point. Depending on when and if we get more fine-grained recompilation avoidance strategies this may matter there as well.)

**Comment by leodemoura** [comment] 2024-03-02 21:28
> Although that's now “domain specific knowledge”, a fair bit different than “robust representation of text”.

I viewed both of them as `#guard_msgs` annoyances. If someone invests time to fix one, it is not much extra work to fix both :) 

> Part of me would prefer if we make the MVars names more stable. Using a fresh name generator per command maybe (if not already the case)

A fresh name generator per command would not help the annoyance being fixed by `exec_capture`
Before the `exec_capture` workaround above, tests would break whenever we made a change that affected the number metavariables being created. 

> normalizing then at some point.

Normalization is a better approach. We would also need a flag to disable normalization. We would also need to control its scope. For example, in a trace containing many metavariables, we must have the property that each metavariable has the same representation. Naive normalization per `ppExpr` backfired in the past, and made traces way less useful.

**Comment by digama0** [comment] 2024-03-04 05:35
This was a deliberate design, in order to catch whitespace regressions and trailing whitespace in suggestions and messages. The default whitespace normalization is very conservative and essentially only exists to allow for additional line breaks in the docstring. But an option in `#guard_msgs` to normalize whitespace would be a reasonable addition.

**Comment by nomeata** [comment] 2024-03-04 09:19
If the goal is to catch whitespace regressions and trailing whitespace in suggestions and messages, wouldn’t it be better to make trailing whitespace actually visible in the output (and, as a side effect, fixing the present bug)?

**Comment by digama0** [comment] 2024-03-04 17:21
Sure, what's your proposal for that?

**Comment by nomeata** [comment] 2024-03-04 17:52
My proposal would be to use `⎵`, willing to accept ambiguity if that is indeed a trailing output of a command.

**Comment by Kha** [comment] 2024-03-05 09:19
I don't understand the need for replacement characters. If we don't care about trailing whitespace in messages, then we should normalize them away in the comparison. If we do care about them, why would the expected output ever be something other than "there should not be trailing whitespace"?

**Comment by Kha** [comment] 2024-03-05 09:57
A normalization toggle seems to be sufficient for that case afaics

**Comment by kmill** [comment] 2024-03-06 01:00
> [ ... mvar normalization ...]
> It would be great to have the same feature at `#guard_msgs`

To throw out a design, it could be that `#guard_msgs` could take in its configuration a list of `String -> String` transformers that are all applied to both the docstring and to the generated messages. Whitespace normalization would be one of the transformers that's included by default, but you could also add in a `?m.123`-to-`?m` transformer.

In another direction, one idea I had, but never fully worked out, was being able to include wildcards in the docstring. A basic version is that you could include a wildcard (like `???`, which would be configurable) that allows any substring. Maybe there'd be multiple kinds of wildcards, depending on whether you want to allow whitespace or not. A more sophisticated version could somehow embed regexes. A weakness to wildcards is that the code action becomes less useful.

**Comment by nomeata** [comment] 2024-03-06 08:37
Maybe useful for other things, but the itch described in this issue doesn't deserve such complexity, and IMHO not even a user-facing option. I'll cook up a PR today that highlights trailing space in a robust and unambiguous way.

**Closed** 2024-03-12 17:14 UTC
Labels: bug
