### ISSUE TITLE
Meta.inferType fails at transparency all

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#5562] opened 2024-10-01 13:27 UTC
The `Meta.inferType` function sets the transparency to `.default`, even if it was set to `.all`, preventing “kernel-close” meta-programming where one wants all definitions to be transparent.

Presumably using `withAtLeastTransparency` is the right fix here (PR coming).

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by kmill** [comment] 2024-10-01 15:35
This seems to be a duplicate of #2194

**Comment by nomeata** [comment] 2024-10-01 16:01
Thanks, that’s useful. In particular the note about the caches.

It seems that `checkFunInfoCache` already takes the current transparency into account (which was a bit silly before, but is useful now). `checkInferTypeCache` should then do the same (at least until and when we use `.all` everywhere, which I’d like to not drag into this bu fix).

**Closed** 2024-10-04 13:29 UTC
Labels: bug
