### ISSUE TITLE
#synth silently succeeds if given nonsense

### ISSUE THREAD

**Issue by eric-wieser** [leanprover/lean4#3214] opened 2024-01-24 14:01 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

The following code emits no diagnostics:
```lean
class Foo (α : Type)

variable {α : Type} (s : Missing α)

#synth Foo s
```

### Context

[Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/.23synth.20is.20ignoring.20me/near/417649900)

### Steps to Reproduce

1. Run the above code

**Expected behavior:** `#synth` should either report an info message or a failure message

**Actual behavior:** Nothing happens.

### Versions

4.5.0-rc1

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by digama0** [comment] 2024-01-27 05:29
looks like a duplicate of #2226

**Comment by eric-wieser** [comment] 2024-01-27 05:55
"duplicate" is perhaps a little strong, but I agree these probably have the same root cause; well spotted!

**Closed** 2024-06-06 13:43 UTC
Labels: bug
