### ISSUE TITLE
Default args for nested inductive constructors

### ISSUE THREAD

**Issue by JamesGallicchio** [leanprover/lean4#4867] opened 2024-07-30 06:53 UTC
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

For nested inductive types, any nested-inductive arguments to the constructors can't be assigned a default value.

### Steps to Reproduce

```
inductive Foo
| mk (x : Array Foo := #[])
```

**Expected behavior:** It should compile, and `Foo.mk` should have a default value for `x`.

**Actual behavior:** An error is thrown:
```
application type mismatch
  optParam _nested.Array_1 #[]
argument has type
  Array Foo
but function has type
  _nested.Array_1 → Type
  ```

### Versions

Reproduced on
- 4.9.0-nightly-2024-05-25
- 4.11.0-nightly-2024-07-29

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment] 2024-08-01 11:36
duplicate of #4824

**Closed by Kha** 2024-08-01 11:36 UTC
Labels: bug
