### ISSUE TITLE
`failed to synthesize instance` in inductive definition

### ISSUE THREAD

**Issue by fpfu** [leanprover/lean4#1373] opened 2022-07-26 12:17 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Steps to Reproduce

```lean
class Foo (d: Nat)
inductive Bar [i: ∀ d', d ≤ d' → Foo d']
| mk: Bar 
```

**Expected behavior:** example should probably work because corresponding Lean3 code works:

```lean
class Foo (d: ℕ)
inductive Bar {d: ℕ} [i: ∀ d', d ≤ d' → Foo d']
| mk: Bar  
```

**Actual behavior:** get an error message:

```
failed to synthesize instance
  (d' : Nat) → ?m.42 ≤ d' → Foo d'
```

explicit passing of instance argument results in another error:

```lean
class Foo (d: Nat)
inductive Bar [i: ∀ d', d ≤ d' → Foo d']
| mk: Bar (i:=i)
```

```
(kernel) declaration type mismatch, 'Bar.mk.sizeOf_spec' has type
  ∀ {d : Nat} [i : (d' : Nat) → d ≤ d' → Foo d'], 1 = 1
but it is expected to have type
  ∀ {d : Nat} [i : (d' : Nat) → d ≤ d' → Foo d'], sizeOf Bar.mk = 1
```

**Reproduces how often:** 100%

### Versions

`nightly-2022-07-26`

**Comment by leodemoura** [comment] 2022-07-26 15:29
Note that the following does not work in Lean 3
```lean
example {d : ℕ} [i : ∀ d', d ≤ d' → Foo d'] : ∀ d', d ≤ d' → Foo d' :=
  infer_instance
```
as the follows does not work in Lean 4
```lean
example [i : ∀ d', d ≤ d' → Foo d'] : ∀ d', d ≤ d' → Foo d' :=
  inferInstance
```
This is the expected behavior.

I am investigating the issue with the `sizeOf` instance generator.

**Comment by leodemoura** [comment] 2022-07-26 18:01
I investigated the `sizeOf` issue. The problem is that the generated `sizeOf` instance for `Bar` has type
```lean
instance {d : Nat} [i : (d' : Nat) → d ≤ d' → Foo d'] : SizeOf` Bar :=
...
```
Since we cannot synthesize `[i : (d' : Nat) → d ≤ d' → Foo d']` is not ever applied.
When we try to generate the lemma, the `sizeOf` default instance (constant function that returns `0`) is used instead. That is, `sizeOf Bar.mk = 0` because the default instance was used.
One possible fix for this issue is to write to change the instance to
```lean
instance {d : Nat} {i : (d' : Nat) → d ≤ d' → Foo d'} : SizeOf` Bar :=
...
```
This is fine since `i` is an implicit argument in `Bar`.
That being said, I think we should add some checker that rejects local instances such as
`[i : (d' : Nat) → d ≤ d' → Foo d']`

**Comment by leodemoura** [comment] 2022-07-26 19:45
The commit above fixes the `SizeOf` issue.

**Closed** 2022-07-27 23:15 UTC

**Comment by leodemoura** [comment] 2022-07-27 23:18
The commit above adds a new local instance validator. It will reject parametric local instances with parameters without forward dependencies. The TC procedure cannot effectively use this kind of local instance. That being said, you can disable the check by using `set_option checkBinderAnnotations false`.
