### ISSUE TITLE
Go to definition does not work at end of identifier

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#767] opened 2021-11-04 21:46 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

I have a little external math function called factorial and when I do goto definition with the cursor at the end of the word it does not work right.

![image](https://user-images.githubusercontent.com/18707114/140424079-a556438f-be16-45d3-9b9b-4aa6a2d9cd0d.png)

### Steps to Reproduce

1. double click the word "factorial" to select the whole word
2. press F12 to goto definition

**Expected behavior:** [What you expect to happen]
Should work and take my to my factorial function, but  it only works if I move the cursor left 1 char so it is "inside" the word "factorial".

**Actual behavior:** [What actually happens]
Fails to find it.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

commit 89ab3cadf987c7ad005f34b0b744066e2e9c2402

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by Kha** [comment] 2021-11-05 07:24
This is problematic in the presence of custom notation. Should `⟨factorial|⟩`, where `|` is the cursor position, go to `factorial` or to the definition of the anonymous constructor? We could make it work only when not followed directly by another token though.

**Comment by leodemoura** [comment] 2021-11-05 16:39
> This is problematic in the presence of custom notation. Should `⟨factorial|⟩`, where `|` is the cursor position, go to `factorial` or to the definition of the anonymous constructor? We could make it work only when not followed directly by another token though.

@Kha I think this is a good compromise.

**Comment by larsk21** [comment] 2021-12-03 15:28
> This is problematic in the presence of custom notation. Should `⟨factorial|⟩`, where `|` is the cursor position, go to `factorial` or to the definition of the anonymous constructor? We could make it work only when not followed directly by another token though.

This is already inconsistent in the current implementation (using VSCode). When typing `⟨factorial|⟩` (with the cursor at the `|`) VSCode will highlight the word `factorial`, while the hover at the same position will show the info for  `⟨⟩`.

**Comment by Kha** [comment] 2021-12-03 15:45
Thanks, good to know. Alternatively we could always prefer identifiers over adjacent tokens.

**Comment by Kha** [comment] 2021-12-03 16:23
Then maybe the current behavior isn't too bad since at least it is consistent. I don't think I've ever used go-to-definition with a selection to be honest (if your hand is already on the mouse, why not use Ctrl + click?).

**Comment by Kha** [comment] 2021-12-03 16:27
Ah, I forgot about your comment that it is already inconsistent right now in VS Code. I would be okay with any of the comprise solutions or the current behavior at this point.

**Comment by leodemoura** [comment] 2022-03-20 14:27
@Kha What is the plan for this issue? You made a suggestion above, Lars raised a new concern, then you said "maybe the current behavior isn't too bad". I don't have a preference here, I am happy to close it with "wontfix", or try to fix it.

**Comment by Kha** [comment] 2022-03-20 14:36
I still don't really understand the original use case of selecting the identifier first, so I'm okay with closing.

**Comment by lovettchris** [comment] 2022-03-21 18:05
The user scenario is you use "find" to find something then you want to press F12, but it doesn't work because find selects the whole word, leaving the caret at the end of the word.  Can the LSP fix this internally by just subtracting 1 from the position if it is at the end of a word and there is a following whitespace?

The other thing that is funky is the the tooltip shows it was looking for "append" and that's very confusing now, because we all know Array.append exists:

![image](https://user-images.githubusercontent.com/18707114/159336368-7dfb0414-20d5-4a6b-8730-59d6bc6b4dd6.png)

**Comment by Kha** [comment] 2022-03-22 08:53
Thanks for elaborating, that makes more sense. Is the use case still relevant now that we have workspace symbol search?

**Comment by lovettchris** [comment] 2022-03-22 20:24
Customers will complain because the Lean implementation of goto definition is non-standard.  I vote we should fix it before that happens.

**Comment by leodemoura** [comment] 2022-03-24 00:48
I think Chris' user scenario is realistic, and I can reproduce it.
I am removing the "closing soon".

**Closed** 2022-05-30 09:16 UTC

**Comment by lovettchris** [comment] 2022-05-30 18:10
woot!
