### ISSUE TITLE
Tactic sequence parsing after `case` not heeding indentation

### ISSUE THREAD

**Issue by nomeata** [leanprover/lean4#3456] opened 2024-02-22 13:35 UTC
Consider
```
example (n : Nat) : n = n := by
  induction n
  case zero => rfl
  ‸
```

The natural thing to do next is to move the cursor to the next line, aligned with the `case`, as shown. But then the proof state is
```
Tactic state
No goals
```

If I de-indent once more, to
```
example (n : Nat) : n = n := by
  induction n
  case zero => rfl
 ‸
```
I see what I want to see: The list of still open goals
```
Tactic state
1 goal
n✝: Nat
n_ih✝: n✝ = n✝
⊢ Nat.succ n✝ = Nat.succ n✝
```

But de-indenting further left seems wrong here.

It does not happen with `·` nor `next`; there we get the desired behavior.

Maybe the parser for `case` can be adjusted accordingly.

(@david-christiansen  and I stumbled over this while preparing a tutorial.)

### Versions

`4.6.0-rc1`

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by fpvandoorn** [comment] 2024-03-07 10:59
I think this is a duplicate of #2881?

**Comment by nomeata** [comment] 2024-03-07 11:12
Likely, thanks!

**Closed** 2024-03-07 11:12 UTC
Labels: bug, parser, new-user-papercuts
