### ISSUE TITLE
Hover fails on `rw`

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#1403] opened 2022-08-01 18:19 UTC
```lean
example : True := by
  rewrite []
--^ textDocument/hover     -- fails
  rw []
--^ textDocument/hover     -- fails
  erw []
--^ textDocument/hover     -- works
  simp []
--^ textDocument/hover     -- works
```
Go to definition works on both of them, but the hover only appears on `simp`.

Other tactics with hover irregularities:
* `calc`, `delta`, `match`, `unfold`: shows the elab, not the syntax
* `rw`, `rewrite`: no hover
* `conv`: no hover
* `{ tac }`: no hover
* `. tac`: no hover
* `· tac`: no hover except the unicode help

The first group implies that the elab doc string is taken by preference to the syntax doc string when both are available. I would argue that this is the wrong preference, because if a tactic is implemented as a macro, especially if it has complex control flow, the first elab tactic to run may have very little to do with the actual tactic that was called. (I'm not sure whether this reasoning should also extend to go-to-definition.)

**Comment by leodemoura** [comment] 2022-08-01 19:25
The commit above fixes only the missing hover for `rewrite` and `rw`. 
Moreover, it currently displays the doc string for `rewrite` when hovering over `rw`.

**Comment by leodemoura** [comment] 2022-08-01 19:46
> The first group implies that the elab doc string is taken by preference to the syntax doc string when both are available.

Happy to change it and give preference for syntax doc strings. @kha What do you think?

**Comment by leodemoura** [comment] 2022-08-01 20:06
The commit above fixes the hover for `{ tac }`. 
Both `. tac` and `· tac` both show the doc string for `{ tac }` because they expand into it, and use then `%$id` notation for copying source information from `.` to `{`. 
@Kha This is related to the issue we discussed last week: the `%$id` feature is not creating synthetic positions.

**Comment by Kha** [comment] 2022-08-01 22:12
> @Kha This is related to the issue we discussed last week: the `%$id` feature is not creating synthetic positions.

Yeah, let's fix that https://github.com/leanprover/lean4/pull/1405

**Comment by leodemoura** [comment] 2022-08-04 01:07
> > The first group implies that the elab doc string is taken by preference to the syntax doc string when both are available.
> 
> Happy to change it and give preference for syntax doc strings. @Kha What do you think?

@Kha Ping :)
AFAICT, this is the only pending issue here.
I am happy to make the change.

**Comment by Kha** [comment] 2022-08-04 08:17
Ah, no, this works as intended since a single syntax can have multiple elaborators, so the elaborator docstring is expected to be the more specific one we should show and jump to first. The concern

>  if a tactic is implemented as a macro, especially if it has complex control flow, the first elab tactic to run may have very little to do with the actual tactic that was called

does not apply as the language server disregards info nodes with synthetic positions, which should be the case for the "actual tactic" in this case, especially now that we've restored the original original/synthetic distinction with the above fix.

**Comment by digama0** [comment] 2022-08-04 11:10
> Ah, no, this works as intended since a single syntax can have multiple elaborators, so the elaborator docstring is expected to be the more specific one we should show and jump to first.

I still disagree with this reasoning. When a single syntax has multiple elaborators, from the user's perspective it is one tool that does multiple things, not multiple tools with a complicated overloading setup between them. Most tactics that explicitly take advantage of this kind of extensibility, like `decreasing_trivial`, are intended to have a specific job and the extensions are just more ways to accomplish that job. If `decreasing_trivial` happened to call `trivial` on this run, that doesn't mean that `trivial` would make a suitable replacement for `decreasing_trivial` in this instance, because it might be called multiple times or stored, and if someone hovers over `decreasing_trivial` and gets the documentation for `trivial` they will be very confused.

**Comment by Kha** [comment] 2022-08-04 13:05
Please see above, ``macro_rules `(tactic| decreasing_trivial) => `(tactic| trivial)`` will **not** show the docstring of `trivial`. And partial extensions of tactic are not the only application for a new macro or elab rule, you could also use them to completely replace the prior implementation (especially in categories other than `tactic` that do not backtrack between elaborators). In which case the elaborator docstring seems like a great place to document why you did that.

In the end, the question is whether there is a sensible use case for applying docstrings to both a syntax and its elaborator but expecting (only) the first one to be shown to the user. Especially considering the inconsistency of not showing the docstring of the declaration go-to-definition would jump to (because not jumping to the elaborator would for sure be a clear downgrade).

**Comment by digama0** [comment] 2022-08-04 13:14
> In the end, the question is whether there is a sensible use case for applying docstrings to both a syntax and its elaborator but expecting (only) the first one to be shown to the user. Especially considering the inconsistency of not showing the docstring of the declaration go-to-definition would jump to (because not jumping to the elaborator would for sure be a clear downgrade).

From a doc writer's perspective, it is a lot harder to write good elab comments than syntax comments, because when you are documenting a tactic like `simp` you really want *all* the syntactic variants to be documented there, not spread over multiple comments where the user never gets the full picture. It's already hard enough with cases like `simp!` that used to be syntax flags and have been upgraded to entirely separate tactics with an entirely separate docstring; I feel the problem of fragmented documentation will get much worse if every elab gets its own docstring.

When I'm writing an elab docstring, I usually want it to be code-reader-facing, so I would write something like "Elaborator for the simp tactic. This definition handles the case where there is a sequence of lemmas in the brackets but there is no location argument", yada yada. It's not clear how to do something useful there and also simultaneously be a useful user-facing docstring that's explaining what simp in general does (because all user facing elaborators for simp would want to have that blurb on them in case the user hovers on the wrong thing).

**Comment by leodemoura** [comment] 2022-08-07 15:43
> The first group implies that the elab doc string is taken by preference to the syntax doc string when both are available. I would argue that this is the wrong preference,  ...

Let's create a new RFC for this pending issue, and close this one. Both @Kha and @digama0 made good points. It would be great to get more feedback and ideas on what to do about the pending issue.

**Comment by leodemoura** [comment] 2022-08-07 16:45
Moved discussion for the pending issue to https://github.com/leanprover/lean4/issues/1443

**Comment by leodemoura** [comment] 2022-08-14 01:27
AFACIT, all issues described here have been fixed. The last one was #1443.

**Closed by leodemoura** 2022-08-14 01:27 UTC
Labels: bug
