### ISSUE TITLE
No way to stream all widget messages of a file

### ISSUE THREAD

**Issue by Kha** [leanprover/lean4#2367] opened 2023-07-28 08:47 UTC
For non-interactive messages, we push all message so far to the client after each command using the standard `publishDiagnostics` notification (which itself is not ideal as we must repeat previous messages). For widget messages, we only have the RPC call `getInteractiveDiagnostics` that, when not called with with a line range, blocks until the entire file is processed. That is a quite significant regression.

@Vtec234 Thoughts on how to address this? I assume there is no "push" model in the RPC yet?

**Comment by Kha** [comment] 2023-07-28 09:04
It is not clear to me why we have these two separate message listing interfaces instead of a "get me an interactive version of this message" request since the client has to keep the noninteractive list around anyway for standard LS behavior.

**Comment by gebner** [comment] 2023-07-28 18:14
As you've mentioned in the [Zulip thread](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lean.204.20Toolchain.20much.20bigger.20than.20lean3/near/379406405), this only affects the "all messages" panel in vscode.  That's the only place where the blocking RPC call is used.

**Comment by Vtec234** [comment] 2023-07-28 18:47
> get me an interactive version of this message

For this I think we would need to keep track of some 'message UUID' which the client can reference in order to retrieve its interactive version. In LSP, this could be stored in the `Diagnostic.data` field.

But as Gabriel rightly points out, the issue is not so much with the API as it is with how we use it in the infoview client. Saying 'get me an interactive version of all the messages at this range' is essentially as good as 'get me an interactive version of this message' if the range is fine enough. The client should not use the blocking give-me-all-messages call.

**Comment by Vtec234** [comment] 2023-07-28 19:24
The issue reported on Zulip should be fixed in `vscode-lean4` [here](https://github.com/leanprover/vscode-lean4/commit/65deda60f1e2fee242335b8276fc837014c07a11).

**Comment by Kha** [comment] 2023-07-28 19:32
> For this I think we would need to keep track of some 'message UUID'

Would the list index and, for validation, the document version not be sufficient?

> Saying 'get me an interactive version of all the messages at this range' is essentially as good as 'get me an interactive version of this message' if the range is fine enough.

I suppose so :) . Thanks for implementing it! I guess this issue is effectively solved then.

**Closed** 2023-07-29 15:33 UTC
Labels: enhancement, server

**Comment by Kha** [comment] 2023-07-29 15:43
I do have one more basic question: if we're sending out the non-interactive messages anyway, and already include non-standard fields in them, and if `Diagnostic` and `InteractiveDiagnostic` are identical except for the `message` field, why don't we send out the interactive message as another (optional) extension of the basic `Diagnostic` instead of providing two separate lists?

**Comment by Kha** [comment] 2023-07-29 20:13
I'm afraid I'm left only with even more basic questions: What, ultimately, is the task of an RPC session? Why does it need a lifetime independent (well, a subset of) the worker lifetime? Should it be seen as a kind of arena to guard against unclean exits of RPC clients? I didn't immediately find an answer to this in the code or initial PR.

**Comment by Vtec234** [comment] 2023-07-30 00:39
@Kha:

> Edit: sent this out too quickly, I assume mixing the LSP and RPC protocols could become complicated; see also https://github.com/leanprover/lean4/pull/596#pullrequestreview-720945831

Yes, if I remember correctly we never worked out how ownership should work in the case of pushed data (indeed, afaict there are no RPC references being pushed anywhere in the API right now). With 'pull' it is clearer: whichever code in the client made the RPC call now owns the reference and is responsible for freeing it later.

> Should it be seen as a kind of arena to guard against unclean exits of RPC clients?

Afair (it's been a while), this is more or less correct. The infoview client can be killed and start up again many times over the lifetime of a file worker. In such cases the RPC session for that instance of the client should be dropped eventually: either because the keepalive period expires, or (after we moved RPC keepalive code from infoview to the extension) because the extension drops the RPC session when the webview is disposed.

Do you have concerns about the design or are thinking of a redesign? I would be happy to discuss more, it'd just require fetching much more of this stuff back into mental cache :)

**Comment by Vtec234** [comment] 2023-07-30 00:45
> Why does it need a lifetime independent (well, a subset of) the worker lifetime?

Another reason came back to me: in cases when the *worker* dies and restarts, and the client makes an RPC call with some old references it had from the original worker, we wanted that call to fail immediately rather than having the RPC reference ID refer to some new, unrelated data. This is a bit of a strawman now that reference IDs are randomized (accidental reuse is astronomically unlikely), but it does work as a quick check for 'oops, we have some outdated references around'. From this perspective the RPC session is unique to a (worker, client) pair and is identifying the worker, too.
