### ISSUE TITLE
`Eq` behaves differently from `_=_`

### ISSUE THREAD

**Issue by MiddleAdjunction** [leanprover/lean4#5910] opened 2024-10-31 23:35 UTC
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [X] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

In the following scenario, `_=_` appears to overreach: it expands a definition
 unnecessarily, leading to an avoidable issue with implicit synthesis:
```lean
def D : Type 1 :=  {α : Type} → α → α
theorem h (d : D) : (d : D) = d := rfl
```
Running above leads to the following error:
```
type mismatch
  d
has type
  ?m.23 → ?m.23 : Type
but is expected to have type
  {α : Type} → α → α : Type 1
```
However, surprisingly replacing `_=_` with `Eq` fixes the problem:
```lean
def D : Type 1 :=  {α : Type} → α → α
theorem h (d : D) : Eq (d : D) d := rfl
```

### Context

I raised this issue on a Discord server (Lean 4 anarchy); the description above summarises the issue fairly well.

### Steps to Reproduce

To reproduce run the two code snippets above.

**Expected behavior:** `_=_` to behave the same as `Eq`

**Actual behavior:**  `_=_` does not behave the same as `Eq`

### Versions

[4.14.0-nightly-2024-10-31]

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment] 2024-11-08 12:15
As written, the title describes intended behavior: `=` uses `binrel%`, which helps for coercions to behave as expected. The issue should likely be rephrased in terms of the actual undesired behavior.

**Comment by Kha** [comment] 2024-11-15 10:27
(closing until then, feel free to edit and ask to reopen, or create a new issue)

**Closed by Kha** 2024-11-15 10:27 UTC
Labels: bug
