### ISSUE TITLE
Linters

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#404] opened 2021-04-14 02:18 UTC
We need many different linters.
- Style violations.
- Common mistakes.
- Bad idioms.
- Potential performance problems.

The different linters can be developed independently of each other, and they are self-contained projects.
Core developers will help with the API and integration.

**Comment by jack-ullery** [comment] 2022-02-22 02:10
Do you want linters for the **Lean** or **C++** code (or both)?

For the C++ code, it wouldn't be very difficult for me to add tools like _clang-tidy_ and _cppcheck_ to the build. 
They could be triggered to only run when `CMAKE_BUILD_TYPE=DEBUG`, for example.

It has been a while since this issue was posted. If you're aware of any Lean targeted linters, I'd like to take a look.

**Comment by digama0** [comment] 2022-02-22 09:21
mathlib has a linter framework: https://leanprover-community.github.io/mathlib_docs/commands.html#linting%20commands . Some of this should probably be incorporated into the core lean 4 distribution, but the details have not been worked out. (My impression is that the issue is primarily about Lean linters, as the C++ code is foundational and both user code and the elaborator itself are mostly written in lean.)

**Comment by digama0** [comment] 2022-10-07 22:23
Let's close this issue now that the linter framework has been implemented, and reopen issues for specific linters.

**Closed by digama0** 2022-10-07 22:23 UTC
Labels: help wanted
