### ISSUE TITLE
Syntax pattern matching on numbers succeeds unexpectedly

### ISSUE THREAD

**Issue by gebner** [leanprover/lean4#801] opened 2021-11-16 13:00 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The pattern `` `(0) `` matches all numbers instead of just zero.

### Steps to Reproduce

```lean
syntax "a" num : term

macro_rules
  | `(a 0) => `("zero")
  | `(a 1) => `("one")

#check a 1
```

**Expected behavior:** The check prints `"one"`

**Actual behavior:** The check prints `"zero"`

### Versions

Nightly from November 12.

**Comment by leodemoura** [comment] 2022-01-26 16:41
BTW, this issue also affects other kinds of literal (e.g., string literals).
```lean
syntax "b" str : term

macro_rules
  | `(b "foo") => `("foo!")
  | `(b "bla") => `("bla!")

#check b "bla"
-- "foo!" : String
```

@Kha Your comment seems to suggest we should reject this kind of pattern, correct? It seems like a useful feature.

**Comment by Kha** [comment] 2022-01-26 16:57
I would prefer making it behave as intended by the user. Doing that in a principled way is roughly as hard as rejecting the match, because it needs all the work mentioned in the link.

We could of course add a simple check for built-in literals to fix these specific examples. It just won't cover the more general case of `syntax "c" ("foo" <|> "bar")`.

**Comment by leodemoura** [comment] 2022-01-27 02:22
> We could of course add a simple check for built-in literals to fix these specific examples. 

I agree. We should add this and close this issue.

> It just won't cover the more general case of syntax "c" ("foo" <|> "bar")

Sure. We cover this one when addressing #638.

**Closed** 2022-01-29 16:40 UTC
