### ISSUE TITLE
`simp` uglifies `ofScientific` pretty printing

### ISSUE THREAD

**Issue by girving** [leanprover/lean4#3194] opened 2024-01-18 12:51 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Scientific literals like `0.123712` pretty print nicely, but `simp only` messes up the pretty printing.  Here's an example with no imports:

```
theorem with_number : (0.123712 : Float) < 0.8482312 := by
  -- Goal print as `0.123712 < 0.8482312`
  simp only
  -- Goal prints as `OfScientific.ofScientific 123712 true 6 < OfScientific.ofScientific 8482312 true 7`
  sorry
```

### Context

[Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/OfScientific.20pretty.20printing.20after.20.60simp.60/near/416555053)

This came up for me because I'm working on tightening some bounds of nonlinear functions, and weird numbers naturally appear.

### Steps to Reproduce

See repro above.

### Versions

```
% lean --version
Lean (version 4.5.0-rc1, commit b614ff1d12bc, Release)
```

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by eric-wieser** [comment] 2024-01-18 15:16
A slightly simpler reproduction is `#simp 0.5`

**Comment by hrmacbeth** [comment] 2024-01-20 04:29
Duplicate of https://github.com/leanprover/lean4/issues/2159?

**Comment by girving** [comment] 2024-01-20 10:17
Yep, duplicate, apologies for not noticing the previous issue.

**Closed** 2024-01-20 10:17 UTC
Labels: bug
