### ISSUE TITLE
Lean is too eager (?) to infer holes, resulting in incorrect fills when unique solutions exist and requests for things of type `sorry`

### ISSUE THREAD

**Issue by JasonGross** [leanprover/lean4#334] opened 2021-03-05 22:33 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```lean
structure Ty where
  ctx : Type
  ty : ctx → Type
structure Tm where
  ty : Ty
  tm : ∀ {Γ}, ty.ty Γ

#check fun (Γ : Type)
(A : Ty)
(Actx : Γ = A.ctx)
(x : Tm)
(xTy : x.ty = A)
=> Eq.rec (motive := fun ty _ => ∀ {Γ:ty.ctx}, ty.ty Γ) (fun {Γ:x.ty.ctx} => x.tm (Γ:=Γ)) xTy

#check fun (Γ : Type)
(A : Ty)
(Actx : Γ = A.ctx)
(x : Tm)
(xTy : x.ty = A)
=> Eq.rec (motive := fun ty _ => ∀ {Γ}, ty.ty Γ) (fun {Γ} => x.tm (Γ:=Γ)) xTy
/-
20:41: application type mismatch
  Ty.ty ty Γ
argument
  Γ
has type
  x.ty.ctx
but is expected to have type
  ty.ctx

20:62: type mismatch
  Tm.tm x
has type
  Ty.ty x.ty Γ
but is expected to have type
  sorry

-/
```

**Expected behavior:** The second `#check` should fill holes in the same way as they are manually filled in the first `#check`

**Actual behavior:** incorrect inference and type mismatches

### Versions

```
$ lean --version
Lean (version 4.0.0-m2, commit 26dda3f63d88, Release)
$ uname -a
Linux JasonGross-X1 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
running on WSL2 in Windows 10

**Comment by leodemoura** [comment] 2021-03-06 03:14
The `sorry` issue was fixed by https://github.com/leanprover/lean4/commit/7a79ef62d1ee7ff34ac3141eacbecb537ec62e28
I didn't investigate the first part yet.

**Comment by leodemoura** [comment] 2021-03-06 17:41
> The second #check should fill holes in the same way as they are manually filled in the first #check

This is due to the presence of higher-order unification constraints.
Lean approximates their solutions. In the second example, it encounters the constraint
```
x.ty.ctx  =?=  ?m.560 ?m.546 (Eq.refl ?m.546)
```
and solves it using the approximation
```
?m.560 := fun (ty : ?m.545) (x_1 : ?m.546 = ty) => x.ty.ctx
```
We do not guarantee that if there is a unique solution, it will be found. 
We also suggest users should not try to manually construct recursors, but use `match`-expressions or tactics (e.g., `cases`, `subst`, and `rewrite`).

**Comment by leodemoura** [comment] 2021-03-06 17:46
I will close this issue since the unification procedure works like that by design, and we don't have any plans to extend it.
It is more general than the Lean 3 one.

**Closed by leodemoura** 2021-03-06 17:46 UTC

**Comment by JasonGross** [comment] 2021-03-06 22:48
I want to push back a bit here; this example shows that Lean's unification is incomplete over the first-order fragment, as the problem is entirely solvable simply by delaying all higher-order constraints until the first-order ones have been resolved.  In particular, `ty.ty Γ` forces `ty : Ty` and `Γ : ty.ctx`.

In fact the problem seems to be that `ty.ty` does not force `ty : Ty`, despite the fact that only `Ty` has a field `ty` which can be applied to an argument.  (Renaming `Tm.ty` to `Tm.ty'` does not change anything, despite the fact then that `Ty` is the only structure with a field named `ty`.)  Replacing `ty.ty Γ` with `Ty.ty ty Γ` makes unification go through fine.  Is it intended that `a.b` does not force the type of `a` even when there is only a single structure with a field `b`?

**Comment by leodemoura** [comment] 2021-03-07 00:28
> I want to push back a bit here; this example shows that Lean's unification is incomplete over the first-order fragment, 
> as the problem is entirely solvable simply by delaying all higher-order constraints until the first-order ones have been resolved. 

I disagree. The constraint is higher-order. The unifier is not "seeing" all constraints at once. 
The constraints are being produced by the elaborator, and the unifier has no idea that later new constraints will be generated, and they will reduce the following one to a first-order constraint.
```
x.ty.ctx  =?=  ?m.560 ?m.546 (Eq.refl ?m.546)
```

> In particular, ty.ty Γ forces ty : Ty and Γ : ty.ctx.

This is not true in Lean. The term `ty.ty` will only be elaborated after we learn the type of `ty` even if there is a single structure with a field `ty`. 

> as the problem is entirely solvable simply by delaying all higher-order constraints until the first-order ones have been resolved. 

We don't delay higher-order unification constraints anymore. This kind of heuristic created counterintuitive behavior in previous versions of Lean. For example, given a higher-order constraint, should we postpone or approximate?
By postponing, we may be delaying the "information flow", i.e., information that we could obtain using an approximate solution. 

BTW, tinkering with the unifier is a quite frustrating job, we often solve new problems, but break other ones.
We wrote some documentation in the following places:
https://github.com/leanprover/lean4/blob/master/src/Lean/Meta/ExprDefEq.lean#L370-L526
https://github.com/leanprover/lean4/blob/master/src/Lean/Elab/Term.lean#L24-L60

Happy to discuss these issues at a Zoom meeting. It is too inefficient here.


In Lean 4, we just postpone the elaboration of certain terms (e.g., dot-notation above, `match`-expressions) when the expected type is not available.

For example, given a higher-order constraint, should we postpone or approximate?
By postponing, we may be delaying failure. We may also be delaying the "information flow", i.e., information that we could obtain using an approximation. 

> Is it intended that a.b does not force the type of a even when there is only a single structure with a field b?

Yes.

**Comment by JasonGross** [comment] 2021-03-07 14:38
> This is not true in Lean. The term `ty.ty` will only be elaborated after we learn the type of `ty` even if there is a single structure with a field `ty`.

Ah, okay.  This is a complete explanation for my confusion on the behavior of unification here.  (Though I am still curious about the reasoning; I guess you want unification to be stable under importing new files which add unrelated structures with the same field name?)

> We don't delay higher-order unification constraints anymore. This kind of heuristic created counterintuitive behavior in previous versions of Lean. For example, given a higher-order constraint, should we postpone or approximate?

I think that all approximate solutions should be postponed until all pattern constraints from a given unification problem have been solved.  Failure to do this in Coq resulted in `rewrite` often failing to instantiate lemmas with obvious instantiations because it processed applications in the wrong order and failed early on unification problems that would later become merely conversion problems.



> We wrote some documentation in the following places:
> https://github.com/leanprover/lean4/blob/master/src/Lean/Meta/ExprDefEq.lean#L370-L526
> https://github.com/leanprover/lean4/blob/master/src/Lean/Elab/Term.lean#L24-L60

Ah, neat!  

> Happy to discuss these issues at a Zoom meeting. It is too inefficient here.

Yeah!  I'd be interested in learning your / Lean's philosophy of unification, and sharing any expertise/insight I have that might be useful to you (I've spent a couple dozen hours thinking and chatting about how to design unification algorithms that are both predictable and powerful, though probably not enough time thinking about how to make unification fast).  When's good for you?

**Comment by leodemoura** [comment] 2021-03-07 15:08
>  I guess you want unification to be stable under importing new files which add unrelated structures with the same field name?

Yes. BTW, the "dot"-notation is quite general in Lean. Example: given `(x : List Nat)`, `x.foldl (.+.) 0` is notation for `List.foldl (.+.) 0 x`.

> When's good for you?

I will send you a message on Zulip.
