### ISSUE TITLE
fin_cases breaks on intervals of Fin

### ISSUE THREAD

**Issue by shortc1rcuit** [leanprover/lean4#4721] opened 2024-07-10 20:34 UTC
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [X] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [X] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

fin_cases fails on some intervals over the type Fin (k + 2)

### Context

See [this thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/fin_cases.20on.20Finset.2EIoc) on the Lean Zulip.

### Steps to Reproduce

```
import Mathlib.Tactic

example (k : ℕ) (x : Fin (k + 2)) (hx : x ∈ Finset.Iic 1) : True := by
  fin_cases hx
```

```
import Mathlib.Tactic

example (k : ℕ) (x : Fin (k + 2)) (hx : x ∈ Finset.Icc 0 1) : True := by
  fin_cases hx
```

**Expected behavior:**
For the first example, two cases should be made, `x = ⊥` and `x = 1`.
For the second example, two cases should be made, `x = 0` and `x = 1`.

**Actual behavior:**
In both examples, it returns the error "(kernel) declaration has metavariables '_example'".

### Versions

Using live.lean-lang.org, lean version 4.10.0-rc2

### Additional Information

More examples of this bug can be found in the thread linked in Context

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by TwoFX** [comment] 2024-07-11 07:28
Hi @shortc1rcuit, thank you for taking the time to report this issue. The `fin_cases` tactic is part of mathlib4, not of Lean itself, so this issue should be reported at https://github.com/leanprover-community/mathlib4/issues instead of here.

I will close this issue. If investigation of the issue in mathlib reveals that it is caused by a Lean bug, please open a new issue here with a mathlib-free reproducer. Thanks!

**Closed by TwoFX** 2024-07-11 07:28 UTC
Labels: bug

**Comment by shortc1rcuit** [comment] 2024-07-11 15:40
Ah my bad, thanks for letting me know!
