### ISSUE TITLE
Widgets: improve `Info` delaboration

### ISSUE THREAD

**Issue by Vtec234** [leanprover/lean4#681] opened 2021-09-19 22:00 UTC
When hovering over source code, the hover spans are determined in the LSP server from [`Info`](https://github.com/leanprover/lean4/blob/c2d33a1a582c4011f5334551b903df85aa32ddc7/src/Lean/Elab/InfoTree.lean) nodes emitted by the elaborator and stored in the `InfoTree`. Parts of the elaborator include special cases to emit the right `Info` for dot notation, `|>` pipes, and other syntactic constructs.

Analogously, in the [upcoming](https://github.com/leanprover/vscode-lean4/pull/37) infoview the spans of hoverable terms are shown exactly where the *delaborator* emits `Info`s. However, we are mostly missing the special cases which means the interactive output will be less accurate than the editor input. This issue is to track where in the delaborator these should be added.

Currently `Info`s are added for structure notation [field names](https://github.com/leanprover/lean4/blob/c2d33a1a582c4011f5334551b903df85aa32ddc7/src/Lean/PrettyPrinter/Delaborator/Builtins.lean#L223), and [generically](https://github.com/leanprover/lean4/blob/c2d33a1a582c4011f5334551b903df85aa32ddc7/src/Lean/PrettyPrinter/Delaborator/Basic.lean#L228) in `delabFor`.

**Comment by Vtec234** [comment] 2021-09-19 22:08
**Partial function application**.

Observe that in the goal state for
```lean
example : id 2 = id 2 := by
```
hovering over `id` shows the full application:

![screenshot](https://user-images.githubusercontent.com/13901751/133944508-c9d2bbd3-0e71-4361-b100-2584c76303c3.png)

Instead, we should have an `Info` node for just `id` there. This would be consistent with source code hovers:

![screenshot](https://user-images.githubusercontent.com/13901751/133944540-fa0b8bae-791e-456f-9345-b33bf67a8fe1.png)

**Comment by tydeu** [comment] 2021-09-23 22:19
@Vtec234 Honestly, I much prefer the type of the full application. One of the annoyances I often have when debugging type errors is that hovering over a type in code does *not* show a function's applied type but rather its bare type -- being able to see what the elaborator inferred for a term is quite helpful. That is, I would personally prefer that this behavior be ported to the source code hovers not the other way around

**Comment by Vtec234** [comment] 2021-09-23 23:06
> One of the annoyances I often have when debugging type errors is that hovering over a type in code does not show a function's applied type but rather its bare type

@tydeu but are you aware that in `f a`, you can hover over the *space* to see the span and type of the full application? This is intentional, because in this model you can check the type of `f` (hover on `f`), of `a` (hover on `a`), and of the whole thing (hover on space). If `f` displays the full type, then the information available is a strict subset of the current.

**Comment by tydeu** [comment] 2021-09-23 23:20
@Vtec234 yes, that works most of the time (sometimes it instead gets confused and shows highlights the syntax of a whole block or whatever instead). I guess my wish is thus the type of the full application and more accurately what I said before -- the inferred type of the function (i.e., `id : Nat -> Nat` for `id 2`). That, however, I guess really isn't in the scope of the PR, so you can probably just ignore me. 😆

**Comment by Vtec234** [comment] 2021-09-23 23:26
Oh right, I missed that subtlety. Yeah, showing the inferred type of the function is still on the books I think. But it is orthogonal to the bug described above which is just missing `Info` nodes.

**Comment by gebner** [comment] 2021-09-29 15:38
I agree with @tydeu that spans should only be shown for full applications in the infoview widgets (this is how it works in Lean 3, and also how we show the expected type).  I believe this is the most useful behavior from a UX point of view: when I hover over a subterm in the infoview I want to see its (implicit and explicit) arguments.  The more arguments I see, the more useful the popup is.

((Hovers in the source code are a different discussion.  One where I also agree with @tydeu btw.  I'd really like to see the type specialized to the implicit arguments in the hover.))

Here are some other common issues I've seen, let me know if I should make separate bug reports:

- The subexpression `k * n` is tagged with an `InfoWithCtx` that produces the following `InfoPopup`, which seems to only describe the first argument `k`:
![infopopup](https://user-images.githubusercontent.com/313929/135301750-5dea50bd-17d5-45a7-921c-1af3e513a974.png)

- I've noticed the RPC error -32603: unknown free variable '_uniq.10' when clicking on the notation for "or", for example. https://github.com/Julian/lean.nvim/pull/123#issuecomment-909791147

**Comment by Vtec234** [comment] 2021-09-30 18:25
> spans should only be shown for full applications in the infoview widgets

@gebner could you please illustrate by example (good spans vs bad spans) what you mean by this?

> separate bug reports

This thread is meant to collate all `Info`-node delaboration issues which this does look like, so let's leave it here.

**Comment by gebner** [comment] 2021-10-01 09:00
> could you please illustrate by example (good spans vs bad spans) what you mean by this?

This was a comment on the `id 2` example above.  `id` by itself should not be selectable.  `id 2` (and `2`) should be, and the hover should show `@id Nat 2` (and `@OfNat.ofNat ....`, resp.)

**Comment by Vtec234** [comment] 2021-10-04 18:14
> I've noticed the RPC error -32603: unknown free variable '_uniq.10' when clicking on the notation for "or"

Should be fixed in #711.

**Comment by gebner** [comment] 2021-10-05 12:18
Another issue is that we don't want a top-level span in the tooltip.  For example if you click on `id 2`, then the tooltip shows `@id Nat 2`, which you can click on again to get `@id Nat 2` etc.

Instead only the function/arguments should have spans: i.e., in the tooltip you can click on `@id` and `Nat` and `2`, but not on `@id Nat 2`.  (This is also how it works in Lean 3.)

**Comment by gebner** [comment] 2021-12-21 21:20
I think we've fixed all the bugs reported here, should we close the issue now?  I feel like the issue is already long enough that it becomes hard to navigate.

**Comment by Kha** [comment] 2021-12-21 21:26
Yeah, let's open individual issues if there's anything left

**Closed by Kha** 2021-12-21 21:26 UTC
