### ISSUE TITLE
Undocumented `let rec` syntax impossible to provide termination proof

### ISSUE THREAD

**Issue by MichaelBurge** [leanprover/lean4#860] opened 2021-12-09 10:45 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Local let bindings can use the undocumented `rec` keyword to allow self-reference, but this is undocumented and doesn't support the `termination_by` syntax that top-level functions support, so they are unnecessarily restricted compared to top-level functions.

[Description of the issue]

### Steps to Reproduce

The following code passes with `partial`, but if removed Lean complains about a missing `termination_by` modifier. I wasn't able to find any example in the Lean4 tests of a `let rec` with `termination_by`, and both `let rec` and `termination_by` are currently undocumented on [this](https://leanprover.github.io/lean4/doc/expressions.html) page despite `let rec` being a "term" in the [parser](https://github.com/leanprover/lean4/blob/f4759c9a223f12bbae779124a5d9ab7bf999032b/stage0/src/Lean/Parser/Term.lean#L174)(and hence an expression).

Passes
```lean
def evenq (n: Nat) : Bool := Nat.mod n 2 = 0

partial def pack (n: Nat) : List Nat :=
  let next (n: Nat) := n / 2;
  let rec loop (n : Nat) (acc : Nat) (accs: List Nat) : List Nat :=
    match n with
    | Nat.zero => List.cons acc accs
    | n => match evenq n with
      | true => loop (next n) 0 (List.cons acc accs)
      | false => loop (next n) (acc+1) accs
  loop n 0 []

#eval pack 27
```

Fails with `termination_by` modifier:
```lean
def evenq (n: Nat) : Bool := Nat.mod n 2 = 0

def pack (n: Nat) : List Nat :=
  let next (n: Nat) := n / 2;
  let rec loop (n : Nat) (acc : Nat) (accs: List Nat) : List Nat :=
    match n with
    | Nat.zero => List.cons acc accs
    | n => match evenq n with
      | true => loop (next n) 0 (List.cons acc accs)
      | false => loop (next n) (acc+1) accs
  termination_by sorry
  loop n 0 []

#eval pack 27
```

**Expected behavior:** [What you expect to happen]

I expect all valid expressions to be documented in the reference manual, and for local let bindings to as expressive as `def` declarations.

**Actual behavior:** [What actually happens]

Local recursive let bindings are undocumented and less expressive than top-level `def` declarations.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time

### Versions
```lean
$ lean --version
Lean (version 4.0.0-nightly-2021-12-08, commit b0fe1e5d10ae, Release)
```

**Comment by MichaelBurge** [comment] 2021-12-09 15:45
Correction: It is documented in the [tactics](https://leanprover.github.io/lean4/doc/tactics.html) section, as an example when using tactics. However, if it's a core expression type with special treatment in the parser, it should be in the syntax reference page linked in the original post.

**Comment by vvs-** [comment] 2021-12-09 19:19
This is incorrect syntax. You should provide `termination_by` on `def` level, i.e after `loop`.

**Comment by leodemoura** [comment] 2021-12-10 17:12
I am closing this issue because it is not a bug. The example linked above shows how to use `termination_by` with a `let rec`. The documentation will be improved in the future.

**Closed by leodemoura** 2021-12-10 17:12 UTC
