### ISSUE TITLE
Make blue sqiggles go away

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#1590] opened 2022-09-12 20:46 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

See [Zulip Thread](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/blue.20squiggly.20lines).

The LSP reports output messages (e.g. from #eval) as DiagnosticSeverity.information which results in them showing up as blue squiggles and as "Problems" in the VS Code Output tab.  If we switch them to DiagnosticSeverity.hint then the squiggles are replaced with a nice little triple dot you can hover over and the Problems output tab is cleaned up:

![image](https://user-images.githubusercontent.com/18707114/189755290-7cd700da-db71-4ad2-9928-6090dbfeb81c.png)

### Steps to Reproduce

```lean
import Foo

def main : IO Unit :=
  IO.println s!"Hello, {hello}!"

#eval Lean.versionString

#eval main
```
**Expected behavior:** no blue squiggles or problems shown in Problems output tab

**Actual behavior:** blue squiggles and problems shown in Problems output tab

**Reproduces how often:** 100%

### Versions

Lean 4 latest

**Comment by PatrickMassot** [comment] 2022-09-12 21:03
From a semantic point of view, I think that "Information" fits better than "Hint" here. Maybe the proper solution is some theme customization?

**Comment by lovettchris** [comment] 2022-09-12 23:34
The user doesn't really see whether it is "information" or "hint" though right?  It's just how we choose to map things to the LSP protocol.

**Comment by digama0** [comment] 2022-09-13 20:30
The user does see "information" vs "hint" quite clearly, as you've observed: "information" shows up with the info icon in the Problems view. They are eye catching and bring your attention to them from anywhere in the project, which is exactly the intended behavior for something that is the equivalent of a write to stdout. "Hint" can only be seen when you happen to be looking in the area (there is no global list of them AFAIK) and plays a role more similar to code lens or other local information gathering.

That is all to say that I agree with Patrick: lean is using the correct mechanism to signal the output of output-producing operations in the IDE. If you want to make the blue squiggles go away, stop writing `#eval` and `#check`.

**Comment by leodemoura** [comment] 2022-09-19 00:05
Closing this issue. See feedback above.

**Closed by leodemoura** 2022-09-19 00:05 UTC

**Comment by lovettchris** [comment] 2022-09-19 16:17
end of discussion then I guess.  What I was going to say is the #eval and #check show up in the InfoView, why do we need them to also be listed as "problems" when they are not problems?

**Comment by digama0** [comment] 2022-09-19 16:50
That's something to take up with VSCode. Then again, I don't know what other title would be more appropriate besides `Diagnostics` which is it's own kind of jargon.

**Comment by lovettchris** [comment] 2022-09-19 16:53
So I take it emacs doesn't have this issue?  Emacs does not show LSP "info" in a "Problems" list?
