### ISSUE TITLE
elab_as_elim does not support function application in resulting motive arguments

### ISSUE THREAD

**Issue by JamesGallicchio** [leanprover/lean4#4086] opened 2024-05-07 09:05 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

I would like to mark the following lemma `elab_as_elim`:
```lean
theorem natAbs_elim {motive : Nat → Prop} (i : Int)
  (hpos : ∀ (n : Nat), i = n → motive n)
  (hneg : ∀ (n : Nat), i = -↑n → motive n)
  : motive (Int.natAbs i)
  := by sorry
```
in order for `apply` to succeed at e.g.:
```lean
example (x : Int) (y : Nat) : x.natAbs < y := by
  apply natAbs_elim x
  sorry
```

However currently the `elab_as_elim` annotation fails with
```lean
unexpected eliminator resulting type
  motive i.natAbs
```

### Context

Zulip thread: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/apply.20motive.20failure

### Steps to Reproduce

**Expected behavior:** `elab_as_elim` succeeds on the `natAbs_elim` example

**Actual behavior:** `elab_as_elim` fails on `natAbs_elim`

### Versions

Lean 4.8.0-rc1
NixOS unstable

### Additional Information

N/A

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by nomeata** [comment] 2024-08-23 13:39
So far, lean assumes that elims conclude with a `motive a b c` where the targets are plain parameters, not complex expressions like `Int.natAbs`. This looks like a deliberate design decision to me, and changing this would be nontrivial. By that reasoning I’m inclined to close this as “works as designed”.

Mario says that this used to work differently in lean3. Is this a significant issue here? If so, maybe an RFC would be in order?

**Comment by kmill** [comment] 2024-09-05 18:09
For `induction`/`cases` tactics, one of the issues here is that when you allow arbitrary expressions in the motive application, it's not clear what the major premises are supposed to be anymore.

However, I think it would be a straightforward refactor to support this for `@[elab_as_elim]`, since in the end the major premises don't matter — the procedure just needs to know which arguments contribute to the elaboration of the motive, so that we can eagerly elaborate those before doing expected type generalization. Supporting this feature might even *simplify* the elaborator.

I'd suggest keeping this issue open to track this.

**Closed** 2024-09-28 22:52 UTC
Labels: bug, P-low
