### ISSUE TITLE
`linter.unusedVariables` false negative within `cases`

### ISSUE THREAD

**Issue by ericrbg** [leanprover/lean4#3112] opened 2023-12-23 00:21 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

```lean
theorem a (x : False ∨ False) : True := by
  cases x with
  | inl h => -- no linter
    trivial
  | inr h =>
    trivial
```

Note that these variables don't get linted as unused. On the other hand, if these are written with (e.g.) the Mathlib `obtains` tactic, or just as a term (`theorem a (x : False ∨ False) : True := x.recOn (fun h => trivial) (fun h => trivial)`) they do get linted.

### Context

Zulip discussipon on https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.60cases'.60.20gets.20away.20with.20unknown.20variables. This came about when removing uses of `cases'` in mathlib; it showed that some were not necessary.

### Versions

Lean (version 4.5.0-rc1, commit b614ff1d12bc, Release)
OSX Ventura

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by Kha** [comment] 2023-12-23 13:30
Unfortunately the variable *is* used in the proof term.
```
theorem a : Or False False → True :=
fun (x : Or False False) =>
  @Or.casesOn False False (fun (t : Or False False) => @Eq.{0} (Or False False) x t → True) x
    (fun (h : False) (h : @Eq.{0} (Or False False) x (@Or.inl False False h)) => True.intro)
    (fun (h : False) (h : @Eq.{0} (Or False False) x (@Or.inr False False h)) => True.intro)
    (@Eq.refl.{0} (Or False False) x)
```

**Comment by ericrbg** [comment] 2023-12-23 14:02
Ah, I see; where could this `h` term be used? Should this be flagged as another issue?

**Comment by digama0** [comment] 2023-12-23 21:46
I thought the unused variable linter looked at the syntax, not the proof term though?

**Comment by nomeata** [comment] 2023-12-24 10:19
The extra junk also shows up as, for example, duplication of recursive calls in well-founded recursion, which can look quite confusing to the user. #3024 tries to work around it, but it seems desirable to to avoid such term duplication in the first place.

**Comment by Kha** [comment] 2023-12-24 10:33
> I thought the unused variable linter looked at the syntax, not the proof term though?

The original PR is very helpful for understanding the current design: #1159

**Comment by Kha** [comment] 2024-09-27 09:42
Closing as working as intended

**Closed by Kha** 2024-09-27 09:42 UTC
Labels: bug
