### ISSUE TITLE
unused variable linter sometimes warns on `_`, even though `_x` suppresses the linter

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#5259] opened 2024-09-05 04:55 UTC
### Steps to Reproduce

```
open List

example [Inhabited α] : ∀ {l : List α}, head? l = some a → head! l = a
  | _ :: _, rfl => rfl
--  ^--- unused variable `a`
```

The linter does not complain on 
```
open List

example [Inhabited α] : ∀ {l : List α}, head? l = some a → head! l = a
  | _a :: _, rfl => rfl
```

### Versions

`nightly-2024-09-04`

**Comment by Kha** [comment] 2024-09-12 13:24
Looks like a duplicate of #2830

**Closed by Kha** 2024-09-12 13:24 UTC
Labels: bug
