### ISSUE TITLE
Panic after unexpected syntax in `elab_rules`

### ISSUE THREAD

**Issue by semorrison** [leanprover/lean4#780] opened 2021-11-11 00:47 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```
elab_rules : tactic | `(X) Y => sorry
```

causes

```
PANIC at Lean.Server.Snapshots.Snapshot.infoTree Lean.Server.Snapshots:55:2: assertion violation: s.cmdState.infoState.trees.size == 1
```

### Steps to Reproduce

**Expected behavior:** 

Just the error
```
unexpected syntax
  elab_rules : tactic
  | `(X) Y => sorry
```

**Actual behavior:** 

The error and a PANIC.

### Versions

leanprover/lean4:nightly-2021-11-10

**Comment by Kha** [comment] 2021-11-11 07:39
Duplicate of #776

**Closed by Kha** 2021-11-11 07:39 UTC
