### ISSUE TITLE
ridiculously long instance names

### ISSUE THREAD

**Issue by kbuzzard** [leanprover/lean4#2343] opened 2023-07-21 16:25 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Lean 4's default instance naming algorithm, combined with mathlib's rich mathematics hierarchies, adds up to auto-generated instance names which are 2500 characters or more.

### Steps to Reproduce

1. Make a gigantic topology and algebra hierarchy
2. Do something mathematically innocuous, like putting a normed space structure on a certain space of linear maps.
3. Marvel at the auto-generated name `ContinuousLinearMap.instNormedSpaceContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToNormedFieldIdToNonAssocSemiringContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupModuleSmulCommClass_selfToCommMonoidToCommRingToEuclideanDomainToMulActionToMonoidWithZeroToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingToSMulToZeroToAddMonoidToSMulZeroClassToZeroToSMulWithZeroContinuousSMulToZeroToCommMonoidWithZeroToCommGroupWithZeroBoundedSMulModuleSmulCommClass_selfToMulActionToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToSMulToZeroToAddMonoidToSMulZeroClassToSMulWithZeroContinuousSMulBoundedSMulInstSeminormedAddCommGroupContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToNormedFieldIdToNonAssocSemiringContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupModuleSmulCommClass_selfToCommMonoidToCommRingToEuclideanDomainToMulActionToMonoidWithZeroToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingToSMulToZeroToAddMonoidToSMulZeroClassToZeroToSMulWithZeroContinuousSMulToZeroToCommMonoidWithZeroToCommGroupWithZeroBoundedSMulModuleSmulCommClass_selfToMulActionToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToSMulToZeroToAddMonoidToSMulZeroClassToSMulWithZeroContinuousSMulBoundedSMul`

### Versions

e.g. `Lean (version 4.0.0-nightly-2023-06-20, commit a44dd71ad62a, Release)` (OS independent)

### Additional Information

What prompted me to open this issue was the fact that these instance names now pollute search; any reasonably small string of reasonable characters is a substring of the above instance name. Others are worried about blow-up continuing and causing weird problems down the line. Another observation is that this causes problems with the docs: the [relevant link](https://leanprover-community.github.io/mathlib4_docs/Mathlib/Analysis/NormedSpace/OperatorNorm.html#ContinuousLinearMap.instNormedSpaceContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToNormedFieldIdToNonAssocSemiringContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupModuleSmulCommClass_selfToCommMonoidToCommRingToEuclideanDomainToMulActionToMonoidWithZeroToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingToSMulToZeroToAddMonoidToSMulZeroClassToZeroToSMulWithZeroContinuousSMulToZeroToCommMonoidWithZeroToCommGroupWithZeroBoundedSMulModuleSmulCommClass_selfToMulActionToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToSMulToZeroToAddMonoidToSMulZeroClassToSMulWithZeroContinuousSMulBoundedSMulInstSeminormedAddCommGroupContinuousLinearMapToSemiringToDivisionSemiringToSemifieldToFieldToNormedFieldIdToNonAssocSemiringContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupContinuousLinearMapToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToAddCommMonoidToAddCommGroupToModuleTopologicalSpaceToTopologicalAddGroupAddCommMonoidToContinuousAddToAddGroupToSeminormedAddGroupModuleSmulCommClass_selfToCommMonoidToCommRingToEuclideanDomainToMulActionToMonoidWithZeroToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToTopologicalSpaceToUniformSpaceToPseudoMetricSpaceToSeminormedRingToSeminormedCommRingToNormedCommRingToSMulToZeroToAddMonoidToSMulZeroClassToZeroToSMulWithZeroContinuousSMulToZeroToCommMonoidWithZeroToCommGroupWithZeroBoundedSMulModuleSmulCommClass_selfToMulActionToZeroToNegZeroClassToSubNegZeroMonoidToSubtractionMonoidToDivisionAddCommMonoidToMulActionWithZeroContinuousConstSMulToSMulToZeroToAddMonoidToSMulZeroClassToSMulWithZeroContinuousSMulBoundedSMul) for this instance doesn't allow you to look at the equations for the instance -- you get the message `One or more equations did not get rendered due to their size.`

In community Lean 3 there was a more reasonable algorithm, which unfortunately I do not know the details of, although I do remember that it was changed from the Lean 3.4.2 algorithm (which was sometimes returning instance names which were too short :-) in the sense that they were missing relevant information or in the wrong namespace or something). It would be great to see this more controlled algorithm in Lean 4 before the exponential growth of auto-generated instance names starts to cause weird problems.

**Comment by semorrison** [comment] 2023-08-07 00:45
I would like to pursue option 6. I don't think it is an obstacle that Mathlib currently references unnamed instances by name. No one is happy about this, and it should be a relatively easy refactor to just avoid this.

(I would probably do this by locally modifying Lean to break all of the auto-names in any dumb way, and then fix everything again.)

**Comment by semorrison** [comment] 2023-08-07 02:37
Ah -- I have encountered a problem with using entirely inaccessible names: sometimes we need to `nolint` instances created using `deriving`. The example I found first was in [`Mathlib.CategoryTheory.Limits.Shapes.WidePullbacks`](https://github.com/leanprover-community/mathlib4/blob/44692e22020daf18e17259cb25898407b172e5ec/Mathlib/CategoryTheory/Limits/Shapes/WidePullbacks.lean#L64)
```
/-- The type of arrows for the shape indexing a wide pullback. -/
inductive Hom : WidePullbackShape J → WidePullbackShape J → Type w
  | id : ∀ X, Hom X X
  | term : ∀ j : J, Hom (some j) none
  deriving DecidableEq
#align category_theory.limits.wide_pullback_shape.hom CategoryTheory.Limits.WidePullbackShape.Hom

attribute [nolint unusedArguments] instDecidableEqHom
```
Possibly the correct response to this is to improve the deriving handler!

**Comment by Kha** [comment] 2023-08-07 08:38
> I would like to pursue option 6

I'm very happy to hear that!



> sometimes we need to `nolint` instances created using `deriving`

Should inaccessible declarations be linted at all?

**Comment by digama0** [comment] 2023-08-07 08:44
It would really help if there was a reliable `@[automatically_generated]` attribute like in rust... right now we have half a dozen approximations to this implemented in lean, std and mathlib.

**Comment by eric-wieser** [comment] 2023-08-07 13:10
> using hygiened (i.e. inaccessible) names

My main concern with this approach is that we lose the ability to have conversations on Zulip like:

> A: Do we have the fact that `LinearMap`s form a module

> B: Yes, it's docs#LinearMap.instModuleLinearMap

Without having to first make a PR to give the instance an explicit name if it didn't already have one.

**Comment by digama0** [comment] 2023-08-07 14:46
yes, I am concerned that such options will just push us to never use anonymous instances at all in mathlib, which feels like a failure of the naming heuristic. And with things like `deriving DecidableEq` this is even worse because then we won't be able to use the sugar (unless it gets an option like `deriving DecidableEq (name := instDecidableEqNat)`).

**Comment by gebner** [comment] 2023-08-07 20:16
> Should inaccessible declarations be linted at all?

We have plenty of linters for simp lemmas and type class instances that ensure a property of the whole simp set / instance set.  Simp will apply lemmas whether they are inaccessible or not, so they need to be linted either way.

And tbh this looks like a bug in the derive handler:
```lean
attribute [nolint unusedArguments] instDecidableEqHom
```

**Comment by eric-wieser** [comment] 2023-08-09 14:04
No, because that doesn't tell them "it's only true under assumptions XYZ"

**Comment by kbuzzard** [comment] 2023-08-10 08:20
OK then I vote for making the PR to give the instance an explicit name if it didn't already have one, because I suspect that this is a pretty marginal concern in practice. It is also a step forward from "Yes, it's `docs#<2500 character string>`. 

Is it clear that one would not be able to link to an inaccessible term? Could the answer be "yes it's `docs#inst37`, sorry we don't have an explicit name for it, but the typeclass system knows it so it should just work"? I have no idea about how the docs work.

**Comment by eric-wieser** [comment] 2023-08-10 09:07
> yes, I am concerned that such options will just push us to never use anonymous instances at all in mathlib, which feels like a failure of the naming heuristic. And with things like `deriving DecidableEq` this is even worse because then we won't be able to use the sugar (unless it gets an option like `deriving DecidableEq (name := instDecidableEqNat)`).

In case you missed it, @digama0: #6423 (now merged) seems like a big step along this path to never using anonymous instances.

**Comment by Kha** [comment] 2023-08-10 14:41
> Is it clear that one would not be able to link to an inaccessible term?

I don't know (@hargoniX?) but it would be good to ensure doc-gen4 can reasonably handle them before touching the naming scheme

**Comment by semorrison** [comment] 2023-08-10 23:38
Noting that my PR https://github.com/leanprover-community/mathlib4/pull/6423 was not intended as a vote for "Mathlib should never ever use anonymous instance". Instead it was to decouple Mathlib from the *current* (fairly obviously unsatisfactory) scheme, so that we have room to change the current scheme without having to fix a million regressions in Mathlib.

If we can come up with a good replacement scheme, and implement it, then of course it's great if Mathlib is happy to go back to relying on the automatically generated names!

**Comment by utensil** [comment] 2023-10-09 10:24
> > using hygiened (i.e. inaccessible) names
> 
> My main concern with this approach is that we lose the ability to have conversations on Zulip like:
> 
> > A: Do we have the fact that `LinearMap`s form a module
> 
> > B: Yes, it's docs#LinearMap.instModuleLinearMap
> 
> Without having to first make a PR to give the instance an explicit name if it didn't already have one.

What about choosing a name prefix based on option 2 (linear in the input size) then a short hygiened (i.e. inaccessible) name such as a hash (like the short git commit id) of the name scheme from option 1? e.g. instModuleLinearMap_3e71a6e

This way one can still talk about doc#LinearMap.instModuleLinearMap as it usually jumps to a unique doc, and gracefully downgrade to a search result to disambiguate.

**Comment by hargoniX** [comment] 2023-10-09 13:55
> > Is it clear that one would not be able to link to an inaccessible term?
> 
> I don't know (@hargoniX?) but it would be good to ensure doc-gen4 can reasonably handle them before touching the naming scheme

doc-gen has a custom filter for declarations it is not supposed to render, as long as this filter is made not to trigger on auto-named instances they will keep showing up just fine.

**Comment by kbuzzard** [comment] 2024-01-28 13:17
@kmill what is the situation with #3089 ? It's still a draft?

Someone suggested to me that we write a linter which checks to see if an auto-generated instance name is too long and if so then CI fails and the user is forced to supply a more sensible name. This would be another workaround for this issue but I'd rather see a PR merged which fixes this high priority mathlib issue properly. It's embarrassing to see members of our community answering questions on the Zulip with links to explicit declarations in the docs which are 1000 characters long.

**Closed** 2024-04-13 18:58 UTC
Labels: Mathlib4 high prio

**Comment by kmill** [comment] 2024-04-13 20:31
For the record, here's an explanation of the scheme that I used in #3098:

1. It elaborates the instance's binders and type and then creates a pi type with all of this.
2. It creates something like a Lean 3 pre-expression from this type, deleting all instance arguments, (most) implicit arguments, all universe levels, and the domains to dependent foralls. It leaves implict arguments that are types (except `Sort _`) or type families, to avoid regression with respect to #951. (Note: the resulting expression isn't well-formed anymore.)
3. It essentially follows the Lean 4 algorithm on the resulting expression. But, it skips all subexpressions it has seen before. For top-level pi types, it also uses the pattern `FooOfBar` rather than `ForallBarFoo`. It initializes the set of seen subexpressions with all prefixes of the current namespace that correspond to declarations.
4. The root module of the current module is called the "current project". If there is no component of the name that came from a constant in the current project, then the name gets a project suffix.
5. If after all this the name already exists, it gets a numerical suffix.
