### ISSUE TITLE
Lake segmentation fault

### ISSUE THREAD

**Issue by yangky11** [leanprover/lean4#2632] opened 2023-10-06 21:07 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

I get segmentation faults when running any lake commands, including `lake build` and `lake clean`. The problem only happens when all of the following three conditions are met:

1. The package depends on [LeanInfer](https://github.com/lean-dojo/LeanInfer) or is LeanInfer itself.
2. The package uses `leanprover/lean4:v4.2.0-rc1` (No problem with `leanprover/lean4:v4.0.0`).
3. The package has been built or partially built (No problem with the first run of `lake build`).

### Steps to Reproduce

1. Check out the `LeanInfer-demo` branch of [lean4-example](https://github.com/yangky11/lean4-example/tree/LeanInfer-demo).
2. Edit lean4-example's lean-toolchain file to use `leanprover/lean4:v4.2.0-rc1`.
3. `lake build`
4. Either wait `lake build` to finish or just kill it in the middle. Then run `lake build` for a second time and you'll see `Segmentation fault (core dumped)`. In this state, running any lake command will run into segmentation faults, unless you remove the lakefile.olean of LeanInfer.

### Versions

`Lean (version 4.2.0-rc1, commit a62d2fd49796, Release)`

```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by tydeu** [comment] 2023-10-06 21:55
@yangky11 Most segfaults with Lake generally come from an out-of-date `lakefile.olean`, Since the problem is fixed when you `rm -rf lake-packages`, the LeanInfer `lakefile.olean` is likely out-of-date. Try running `rm lake-packages/LeanInfer/lakefile.olean` and seeing if that fixes the segfault. The bug here is likely that something is amiss in Lake's out-of-date checking of the `lakefile.olean`.

When you say edit the `lean-toolchain` file, do you mean of the LeanInfer package itself or of the workspace (i.e., the package which depends on it)? The former could certainly produce such an error.

**Comment by yangky11** [comment] 2023-10-06 22:59
@tydeu 

> Try running rm lake-packages/LeanInfer/lakefile.olean

Yes, it has a similar effect to `rm -rf lake-packages`.  It fixes the segfault for one time, and the segfaul will appear again in future `lake build`.

> When you say edit the lean-toolchain file, do you mean of the LeanInfer package itself or of the workspace (i.e., the package which depends on it)? The former could certainly produce such an error.

I was talking about lean4-example's lean-toolchain.

**Comment by tydeu** [comment] 2023-10-06 23:22
@yangky11 

> Yes, it has a similar effect to `rm -rf lake-packages`. It fixes the segfault for one time, but the segfault will appear again in future `lake build`.

Are you saying that deleting the LeanInfer's `lakefile.olean` fixes the segfault for the next `lake build`, but the subsequent lake builds, even without further modifying the `lean-toolchain`, still produce segfaults? If so, that is very unexpected and quite confusing. I will need to spend some time figuring out what might be going on there.

**Comment by yangky11** [comment] 2023-10-07 00:44
> Are you saying that deleting the LeanInfer's lakefile.olean fixes the segfault for the next lake build, but that subsequent lake builds, even without further modifying the lean-toolchain, still produce segfaults?

@tydeu Yes, exactly. I'm not sure if this has anything to do with cloud release.

**Comment by semorrison** [comment] 2023-10-15 05:23
Just confirming that I can reproduce the segfault per the instructions.

**Comment by tydeu** [comment] 2023-10-15 06:31
The [segfault](https://github.com/leanprover/reservoir/actions/runs/6503977219/job/17665301079) in the Reservoir testbed for LeanInfer implies that this bug applies to LeanInfer directly. That means the likely source of this problem is likely the `lakefile.olean` for std4, aesop, or LeanInfer. 

@yangky11 The testbed also flagged a separate problem which is that the `aesop-llm` branch and the manifest revision no longer exist in aesop (as the changes were ported to master). I don't think this could be causing the segfault, but as I am stumped as to what is who knows?

**Comment by yangky11** [comment] 2023-10-15 17:58
> The [segfault](https://github.com/leanprover/reservoir/actions/runs/6503977219/job/17665301079) in the Reservoir testbed for LeanInfer implies that this bug applies to LeanInfer directly.

Yes, I just verified that the bug applies to both LeanInfer itself and its dependencies.


> The testbed also flagged a separate problem which is that the aesop-llm branch and the manifest revision no longer exist in aesop 
This is just outdated lake-manifest.json. I just fixed this problem, but it seems to have nothing to do with segfaults.

**Comment by yangky11** [comment] 2023-10-15 18:03
The problem seems to be LeanInfer's lakefile.olean. When working with LeanInfer directly (instead of its dependencies), removing lakefile.olean will fix the segfault (for one time).

**Comment by yangky11** [comment] 2023-10-16 22:53
Since `lean4:v4.2.0-rc2` has been out, I tested using `lean4:v4.2.0-rc2` and the problem still persists.

**Comment by tydeu** [comment] 2023-10-16 23:26
@yangky11 Yean. Unfortunately, debugging segfault issues in Lean is rather hard. There are a lot of moving pieces to this one and there is nothing very clearly amiss that is a likely root cause. I have been thinking about it a lot, but I do not have an answer yet. One thing that could help would be to see if we cannot reproduce a segfault like in a toy setup (i.e. a minimal working example for this bug would be great).

**Comment by yangky11** [comment] 2023-10-17 01:39
@tydeu Thanks! I'll try to simplify LeanInfer to create a minimal example.

**Comment by yangky11** [comment] 2023-10-17 02:39
@tydeu This is a minimal example: https://github.com/lean-dojo/LeanInfer/tree/segfault

It looks like the problem is related to how we check arm64 vs. x64 in lakefile.lean.

**Comment by tydeu** [comment] 2023-10-17 14:40
@yangky11 Ah, that is what I feared it might be. I imagine the problem stems from how we are gluing the lakefile environment to the imported environment. I think we may need to wait for @Kha's expertise to debug this (as he wrote that glue code). However, I may give investigating it myself a try (or work on a workaround).

**Comment by semorrison** [comment] 2023-10-17 22:52
@tydeu could you point to the code that does this gluing? I'm not sure I can help, but as I've been gluing environments together recently for the REPL and lean4checker I would at least be interested.

**Comment by tydeu** [comment] 2023-10-17 23:45
@semorrison The glue code is:

https://github.com/leanprover/lean4/blob/fb0d0245db9bcb9ff649794f57522c52cb80c993/src/lake/Lake/Load/Elab.lean#L97-L119

**Comment by semorrison** [comment] 2023-10-18 01:31
Ooh, okay that is a scarier part of the API than I have previously used. :-)

**Comment by yangky11** [comment] 2023-11-05 17:22
Hi @tydeu, I see a PR related to this issue has been merged. Has the problem been fixed? Will it be part of the next release?

**Comment by tydeu** [comment] 2023-11-05 18:47
@yangky11 `run_io` is part of the latest release candidate (e.g., `v4.3.0-rc1`) and can be used instead of the `elab` currently used by LeanInfer and thereby avoid this error. Thus, this bug should be fixed for LeanInfer! 😄 (`elab` itself stills segfaults, though.)

**Closed** 2023-11-17 18:50 UTC
Labels: bug, Lake
