### ISSUE TITLE
Higher order rewrite fails

### ISSUE THREAD

**Issue by lecopivo** [leanprover/lean4#1049] opened 2022-03-17 10:07 UTC
Rewrite tactic fails to rewrite certain expression involving lambda expressions.

In particular, the second `rw` in `conv => lhs; rw[D_partial]; rw[D_partial]` fails. Introducing function arguments makes the second `rw` succeed, `conv => lhs; rw[D_partial]; enter [f,df,g]; rw[D_partial]`. I believe that the `rw` should succeed even without the extra function arguments.

This is a problem I have encountered while producing some examples in #1041, but it might have fell under a radar as I have spammed that issue a little bit.

mwe:
```
constant D (f : α → β) : α → α → β := λ x _ => f x  -- just an arbitrary definition to provide Inhabited

variable {α β β₁ β₂ γ δ : Type}
variable [Inhabited α] [Inhabited β] [Inhabited γ] [Inhabited δ] [Inhabited β₁] [Inhabited β₂]
variable [Add α] [Add β] [Add γ] [Add δ] [Add β₁] [Add β₂]

instance {α β : Type} [Add β] : Add (α → β) := ⟨λ f g x => f x + g x⟩

 -- default plays role of a zero
@[simp]
axiom add_default {α} [Inhabited α] [Add α] (x : α) : x + default = x
@[simp]
axiom default_add {α} [Inhabited α] [Add α] (x : α) : default + x = x
-- derivative in zero direction is zero
@[simp]
axiom D_default (f : α → β) (x) : D f x default = default

@[simp]
theorem default_eval {α} [Inhabited β] (x : α) : (default : α → β) x = default :=
by
  unfold default; unfold instInhabitedForAll_1; unfold default; simp; done

-- Basic combinators
@[simp]
axiom D_I         
  : D (λ x : α => x) = λ x dx => dx 
@[simp]
axiom D_K (y : β) 
  : D (λ x : α => y) = λ x dx => default 
@[simp]
axiom D_S (f : α → β → γ) (g : α → β) 
  : D (λ x => f x (g x)) = λ x dx => D (f x) (g x) (D g x dx) + D f x dx (g x)

theorem D_partial (f : α → β → γ)
  : D (λ x y => f x y) = λ x dx y => D (λ x' => f x' y) x dx :=
by
  simp; done

theorem D_S_f_g_x 
  : D (λ (f : α → β → γ) (g : α → β) (x : α) => f x (g x)) = λ f df g x => df x (g x) :=
by 
  -- conv => lhs; rw[D_partial]; rw[D_partial] -- fails
  conv => lhs; rw[D_partial]; enter [f,df,g]; rw[D_partial]
  simp; done

theorem D_diag_g₁_g₂ (f : β₁ → β₂ → γ)
  : D (λ (g₁ : α → β₁) (g₂ : α → β₂) (x : α) => f (g₁ x) (g₂ x)) = λ g₁ dg₁ g₂ x => D f (g₁ x) (dg₁ x) (g₂ x) := 
by
  -- conv => lhs; rw[D_partial]; rw[D_partial] -- fails
  conv => lhs; rw[D_partial]; enter [g₁, dg₁, g₂, x]; rw[D_partial]
  simp; done
```

Tested on nightly-2022-03-17

**Comment by leodemoura** [comment] 2022-03-17 23:56
The `rw` tactic is a fancy way of using `Eq.rec`, the elimination principle for equality. Thus, it cannot rewrite under binders because we cannot build a "motive" for the elimination. By using `enter`, you are using function extensionality to enter inside the binder. Note that, Mathlib 4 has a tactic called `simp_rw` that allows one to rewrite under binders. It is a wrapper around `simp`. However, it is not a strictly more powerful `rw` because `rw` can simultaneously replace several occurrences of the term being rewritten, and this is important sometimes in problems containing many dependencies. 
https://github.com/leanprover-community/mathlib4/blob/98deec52d24142e265284c46baa8df4f300d783c/Mathlib/Tactic/SimpRw.lean

I am closing this issue since it is not a bug.

**Closed by leodemoura** 2022-03-17 23:56 UTC

**Comment by leodemoura** [comment] 2022-03-18 00:05
You can also write
```lean
  conv => lhs; simp only [D_partial]
```
Note that, `simp_rw [a, b]` is sugar for `simp only [a]; simp only [b]`
