### ISSUE TITLE
Substring match statement behaves unexpectedy

### ISSUE THREAD

**Issue by nnmm** [leanprover/lean4#3117] opened 2023-12-25 15:33 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that your issue is not already [filed](https://github.com/leanprover/lean4/issues).
    * Reduce the issue to a minimal, self-contained, reproducible test case. Avoid dependencies to mathlib4 or std4.

### Description

Most users probably have the expectation that a Substring behaves like a String in most circumstances. The behavior of match expressions on Substrings is therefore quite unintuitive.

### Context

[Discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Does.20matching.20substrings.20not.20work.3F/near/409821641)

### Steps to Reproduce

```
import Std.Data.String.Basic

def isRed (s : Substring) : Bool := match s with
  | "red" => true
  | _ => false

def redSubstring : Substring := Substring.mk ".red." ⟨1⟩ ⟨4⟩

#eval isRed "red" -- true
#eval redSubstring -- "red".toSubstring
```

Note that `#eval isRed (redSubstring.toString)` returns `true`.

**Expected behavior:**

```
#eval isRed redSubstring -- true
```

**Actual behavior:**

```
#eval isRed redSubstring -- false
```

### Versions

4.5.0-rc1 on Ubuntu 20.04.6 LTS

### Additional Information

-

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by JiechengZhao** [comment] 2023-12-26 07:30
I feel the result is right. The `Substring` is not `String` and will keep the information of the origin `String`.
You can show this via.
```
example  : isRed redSubstring = false := by
  simp only [isRed, redSubstring]
```
then the goal will be.
```
(match { str := ".red.", startPos := { byteIdx := 1 }, stopPos := { byteIdx := 4 } } with
  | { str := "red", startPos := { byteIdx := 0 }, stopPos := { byteIdx := 3 } } => true
  | x => false)
```

You can fix the problem by:
```
def isRed (s : Substring) : Bool := match s.toString with
  | "red" => true
  | _ => false
```

I feel the `Repr` of the `Substring` is not very clear and leads your misunderstanding.

**Comment by leodemoura** [comment] 2024-06-18 17:46
Closing this issue since this is not a bug.

**Closed by leodemoura** 2024-06-18 17:46 UTC
Labels: bug, invalid
