### ISSUE TITLE
notation overloading breaks match syntax

### ISSUE THREAD

**Issue by digama0** [leanprover/lean4#2076] opened 2023-01-30 19:28 UTC
```lean
structure Foo
def Foo.cons : Bool → Foo → Foo := fun _ _ => {}
notation a "::" b => Foo.cons a b

example (x : List α) : Unit := 
  match x with
  | [] => ()
  | a :: b => ()
-- invalid pattern, constructor or constant marked with '[match_pattern]' expected

example (x : List String) : IO Unit := do
  match x with
  | [] => return
  | a :: b => return
-- unsupported pattern in syntax match
--   a :: b
```
This is [currently breaking mathport](https://github.com/leanprover-community/mathport/actions/runs/4037024497/jobs/6940029970), although the more likely fix for now is to get rid of the conflicting notation for `::`.

**Comment by gebner** [comment] 2023-01-30 20:10
Duplicate of #2050

**Closed by gebner** 2023-01-30 20:10 UTC
