### ISSUE TITLE
Improve `do` notation + Info tree interaction

### ISSUE THREAD

**Issue by leodemoura** [leanprover/lean4#1343] opened 2022-07-21 21:03 UTC
Info view and VS Code code block highlight are not behaving properly for `do` blocks.
This issue was reported by Patrick Massot during the Lean Hackton.
Example:
![image](https://user-images.githubusercontent.com/2778936/180314630-a9e79dcc-1556-4445-b28f-c36043e628e1.png)

**Comment by gebner** [comment] 2022-07-22 14:06
Duplicate of #1248.

**Closed by gebner** 2022-07-22 14:06 UTC
Labels: bug
