### ISSUE TITLE
IR check failed in presence of noncomputable

### ISSUE THREAD

**Issue by alexjbest** [leanprover/lean4#1785] opened 2022-10-27 12:28 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Code generator sometimes doesn't correctly flag noncomputaility

### Steps to Reproduce

In this (somewhat) minimal example I believe `def bug` should be marked noncomputable, but the `IR` generator doesn't pick up on this for some reason.
```lean
namespace WellFounded

variable {α : Sort u} {C : α → Sort v} {r : α → α → Prop}

unsafe def fix'.impl (hwf : WellFounded r) (F : ∀ x, (∀ y, r y x → C y) → C x) (x : α) : C x :=
  F x fun y _ => impl hwf F y

@[implemented_by fix'.impl]
def fix' (hwf : WellFounded r) (F : ∀ x, (∀ y, r y x → C y) → C x) (x : α) : C x := hwf.fix F x

end WellFounded

namespace Nat

theorem lt_or_eq_of_le {a b : Nat} : a ≤ b → a < b ∨ a = b := sorry
section find
variable (p : Nat → Prop)

private def lbp (m n : Nat) : Prop := m = n + 1 ∧ ∀ k, k ≤ n → ¬p k

variable [DecidablePred p] (H : ∃ n, p n)

private def wf_lbp : WellFounded (lbp p) := by
  refine ⟨let ⟨n, pn⟩ := H; ?_⟩
  suffices ∀ m k, n ≤ k + m → Acc (lbp p) k from fun a => this _ _ (Nat.le_add_left _ _)
  intro m
  induction m with refine fun k kn => ⟨_, fun | _, ⟨rfl, a⟩ => ?_⟩
  | zero => exact absurd pn (a _ kn)
  | succ m IH => exact IH _ (by rw [Nat.add_right_comm]; exact kn)

protected def find_x : {n // p n ∧ ∀ m, m < n → ¬p m} :=
(wf_lbp p H).fix' (C := fun k => (∀n, n < k → ¬p n) → {n // p n ∧ ∀ m, m < n → ¬p m})
  (fun m IH al => if pm : p m then ⟨m, pm, al⟩ else
      have this : ∀ n, n ≤ m → ¬p n := fun n h =>
        (lt_or_eq_of_le h).elim (al n) fun e => by rw [e]; exact pm
      IH _ ⟨rfl, this⟩ fun n h => this n $ Nat.le_of_succ_le_succ h)
  0 fun n h => absurd h (Nat.not_lt_zero _)

protected def find : Nat := (Nat.find_x p H).1
end find
end Nat

variable (R : Type) [∀ n, OfNat R n]

open Classical

noncomputable
def char : Nat := Nat.find (fun n => (1 : R) = 1) ⟨1, rfl⟩

def bug : R := -- IR check failed at 'bug._rarg', error: unknown declaration 'char'
  match char R with
  | 0 => 1
  | _ => 0
```

**Expected behavior:** message saying `def bug` must be marked noncomputable

**Actual behavior:**  IR check failed

**Reproduces how often:**  100% but seems to need a fairly complicated example

### Versions

nightly-10-25

**Comment by digama0** [comment] 2022-10-27 12:37
minimized:
```lean
noncomputable def char (R : Type) [Add R] : Bool := true
def bug (R : Type) [Add R] : Bool := not (char R)
```

**Comment by leodemoura** [comment] 2022-10-27 23:41
@digama0 Thanks for minimizing the problem. The minimized version makes it clear what the issue is.

@alexjbest We will improve the error message and make it clear code generation failed because `char` is marked as `noncomputable`.

**Comment by alexjbest** [comment] 2022-10-28 09:55
Thanks, and sorry for being so bad at minimizing! All modifications I tried gave the correct error message, so I assumed this problem was somehow more complicated than it appears to actually be :)

**Comment by semorrison** [comment] 2023-09-20 23:27
Here's another example of the same issue, discovered on [zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Two.20.60noncomputable.60.20errors)

```
class More (R : Type) extends Mul R, Add R

def Foo (R : Type) [Sub R] := R

noncomputable instance bar {R} [Sub R] : More (Foo R) := sorry

instance foo {R} [Sub R] : Add (Foo R) := inferInstance
-- compiler IR check failed at 'foo._rarg', error: unknown declaration 'bar'
```

**Comment by BoltonBailey** [comment] 2024-04-29 18:49
Here are [two](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Type.20mismatch.20.60Iff.2Erfl.60.20in.20instance.20defintion/near/435705015) [more](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Compiler.20IR.20check.20failed/near/435953320) examples from Zulip.

**Comment by kbuzzard** [comment] 2024-06-24 07:48
Here's [another one](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/compiler.20IR.20check.20failed.20at.20'List.2EfilterTR.2Eloop.2E_at.2Esupport.2E/near/446419612).

**Comment by LibertasSpZ** [comment] 2024-07-09 05:28
[Yet another example](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/compiler.20IR.20check.20failed/near/450065685) is here. (And indeed a new-user papercut)

**Comment by kbuzzard** [comment] 2024-07-11 08:54
[Here's another](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/unknown.20declaration.20.60CategoryTheory.2ELimits.2Epullback.60/near/450628983).

**Comment by kbuzzard** [comment] 2024-07-21 19:38
[Here's another](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Extending.20distance.20of.20graphs/near/451203486). "This is giving weird errors, I'm not sure what's the problem here."

**Comment by sgraf812** [comment] 2024-08-24 17:12
Here is another rather small example:

```lean
axiom Later : Type → Type
axiom gfix {α : Type} (f : Later α → α) : Later α
def gfix2 {α : Type} (f : Later α → α) : α := f (gfix f)
```

It certainly triggers a related error message (4.10-rc2):

```
compiler IR check failed at 'IGDTT.gfix2._rarg', error: unknown declaration 'IGDTT.gfix'
```

It's certainly annoying, but I can work my way around it by only using concrete instantitations of `gfix` instead of defining `gfix2` (or postulating `gfix2` in the first place).

**Comment by kbuzzard** [comment] 2024-08-24 23:08
Two people caught out by this in one day today: [here's the other](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.E2.9C.94.20compiler.20IR.20check.20failed.20working.20with.20terminal.20objects/near/464905150).

**Closed** 2024-09-07 22:19 UTC
Labels: new-user-papercuts
