### ISSUE TITLE
Surprising name resolution in typeclass arguments in `variable` statements

### ISSUE THREAD

**Issue by YaelDillies** [leanprover/lean4#4373] opened 2024-06-06 09:21 UTC
### Prerequisites

Please put an X between the brackets as you perform the following steps:

* [x] Check that your issue is not already filed:
      https://github.com/leanprover/lean4/issues
* [x] Reduce the issue to a minimal, self-contained, reproducible test case.
      Avoid dependencies to Mathlib or Batteries.
* [x] Test your test case against the latest nightly release, for example on
      https://live.lean-lang.org/#project=lean-nightly
      (You can also use the settings there to switch to “Lean nightly”)

### Description

Typeclass arguments in `variable` statements get annotated with errors that occurred during their elaboration at statements that are arbitrarily far from them, causing confusing non-local errors.

### Steps to Reproduce

Consider the following code:
```
inductive Foo : Type | foo

class Bar (α : Type) where bar : α

instance : Bar Foo where bar := .foo

class Baz {α : Type} [Bar α] (a : α) : Prop where

variable (k : Foo) [Baz k]

inductive Quux.Fu : Type

-- Possibly a lot of code

inductive Quux.Foo : Type
```
and
```
inductive Foo : Type | foo

class Bar (α : Type) where bar : α

instance : Bar Foo where bar := .foo

structure Baz {α : Type} [Bar α] (a : α) : Prop where

variable (k : Foo) (l : Baz k)

inductive Quux.Fu : Type

-- Possibly a lot of code

inductive Quux.Foo : Type
```

**Expected behavior:** Neither of the two code blocks error, or at least error in the same way.
**Actual behavior:** The first code block throws
```
failed to synthesize instance
  Bar Foo
```
on `[Baz k]`. The second one does not.

### Versions

4.8.0

### Impact

Add :+1: to [issues you consider important](https://github.com/leanprover/lean4/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc). If others are impacted by this issue, please ask them to add :+1: to it.

**Comment by leodemoura** [comment] 2024-06-06 14:38
This is an accidental name capture bug. While elaborating `inductive Quux.Foo`, `(k : Foo)` is interpreted as `(k : Quux.Foo)`. We can use `pp.fullNames true` to expose the issue:
```
 error: failed to synthesize
  Bar Quux.Foo
```
Here is an even nastier version where no error is reported, but `def a` is bogus
```
inductive Foo : Type | foo
class Bar (α : Type) where bar : α
instance : Bar Foo where bar := .foo
structure Baz {α : Type} [Bar α] (a : α) : Prop where
variable (k : Foo) (l : Baz k)
inductive Quux.Fu : Type
inductive Quux.Foo : Type
open Quux
def a := l
#print a
-- def a : sorryAx Prop true → sorryAx Prop true := fun l => l
```

**Comment by leodemoura** [comment] 2024-06-06 22:15
> maybe the part of the code relevant to variable elaboration is about to change significantly in a way that will make this bug disappear?

@YaelDillies Correct. This is our current plan.

**Comment by Kha** [comment] 2024-08-16 14:04
Unfortunately #4814 did not change variables sufficiently enough to fix this issue. Actually, I believe this is a duplicate of #1876. As documented there, we unfortunately do not know of a good way to fix this issue.

**Closed by Kha** 2024-08-16 14:04 UTC
Labels: bug
