### ISSUE TITLE
Dependent elimination bug

### ISSUE THREAD

**Issue by DanielFabian** [leanprover/lean4#480] opened 2021-05-21 00:14 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Dependent elimination creates a type-incorrect term when an accessible term is involved, even though there are no variables in the pattern:

### Steps to Reproduce
```lean
axiom f : Nat → Nat

inductive is_nat : Nat -> Prop
| Z : is_nat 0
| S {n} : is_nat n → is_nat (f n)

axiom P : Nat → Prop
axiom F0 : P 0
axiom F1 : P (f 0)
axiom FS {n : Nat} : P n → P (f (f n))

theorem foo : ∀ {n}, is_nat n → P n := fun h =>
  @is_nat.brecOn (fun n hn => P n) _ h fun n h ih =>
  match ih with
  | is_nat.below.Z => F0
  | is_nat.below.S .(is_nat.Z) _ _ => F1
  | is_nat.below.S _ (is_nat.below.S a b hx) h₂ => FS hx

theorem foo' : ∀ {n}, is_nat n → P n := fun h =>
  @is_nat.brecOn (fun n hn => P n) _ h fun n h ih =>
  match ih with
  | is_nat.below.Z => F0
  | is_nat.below.S is_nat.Z _ _ => F1
  | is_nat.below.S _ (is_nat.below.S a b hx) h₂ => FS hx
```

**Expected behavior:** 
both `foo` and `foo'` should compile. 

**Actual behavior:** 
`foo'` fails to compile with a type incorrect term. I don't see any reason according to the dependent elimination algorithm, why this should be failing.

**Reproduces how often:**
always

### Versions
Fairly current master.

### Additional Information
none

**Comment by leodemoura** [comment] 2021-05-22 04:11
`foo'` looks unreasonable to me. In the second alternative, The `is_nat` argument is a pattern, but in the third one, the `is_nat.below` argument is the pattern, and the `is_nat` one is inaccessible.  For me, this is not a bug. We may try to improve the error message, but I think it is unreasonable to expect Lean to change a user provided pattern into an inaccessible one.
Note that the following works as expected.
```lean
theorem foo : ∀ {n}, is_nat n → P n := fun h =>
  @is_nat.brecOn (fun n hn => P n) _ h fun n h ih =>
  match ih with
  | is_nat.below.Z => F0
  | is_nat.below.S _ is_nat.below.Z _ => F1
  | is_nat.below.S _ (is_nat.below.S a b hx) h₂ => FS hx
```

**Comment by DanielFabian** [comment] 2021-05-22 08:35
hmm, if the argument is that the user should never pattern match on the `is_nat` part of the `below`, then I think we should turn it into an implicit. It doesn't strike me like a great idea to have a pattern `Type.ctor _ x y z` where the first argument necessarily always has to be `_`. What do you think?

That would make this thing go away.

On the other hand, here is my mental model how I think about it and why it confused me so much:

I see three cases; `Z`, `S Z`, `S S x`. Whether I write any of the following, in my mind I'm still in the `S Z` case, the RHS is identical so it's confusing to me as to why some of the options would be strictly forbidden:
```lean
is_nat.below.S is_nat.Z _ _
is_nat.below.S .(is_nat.Z) _ _
is_nat.below.S is_nat.Z is_nat.below.Z _
is_nat.below.S .(is_nat.Z) is_nat.below.Z _
is_nat.below.S is_nat.Z .(is_nat.below.Z) _
is_nat.below.S .(is_nat.Z) .(is_nat.below.Z) _
is_nat.below.S _ is_nat.below.Z _
is_nat.below.S _ .(is_nat.below.Z) _
```

Is there any obvious downside to turning `0`-argument constructors into inaccessible patterns for the dependent elimination algorithm? (we could potentially also do it just inside of the algo, if we don't want to translate the patterns up-front for pretty-printing purposes)

**Comment by leodemoura** [comment] 2021-05-22 17:25
> hmm, if the argument is that the user should never pattern match on the is_nat part of the below, then I think we should turn it into an implicit. It doesn't strike me like a great idea to have a pattern Type.ctor _ x y z where the first argument necessarily always has to be _. What do you think?

Yes, it makes sense to make argument implicit when their values are restricted by other explicit arguments. This is the case here.
That being said, the `below` auxiliary construction is not meant to be directly used by users. I would say it is nice to make the argument implicit, but not super important.

> I see three cases; Z, S Z, S S x. Whether I write any of the following, in my mind I'm still in the S Z case, the RHS is identical so it's confusing to me as to why some of the options would be strictly forbidden:

When we provide an explicit pattern, we are telling Lean that you want to perform case-analysis at this point. That is, you are instructing Lean to use a `casesOn` at that point. When an inaccessible pattern is used, you are telling Lean that case-analysis should not be used at that point, and that the value of this particular term is fixed by other terms because of typing rules. 
For me, the biggest problem with your `foo'` example is that you are not consistent where the case-analysis should be performed. The second and third alternatives are doing it in different places.

> Is there any obvious downside to turning 0-argument constructors into inaccessible patterns for the dependent elimination algorithm? (we could potentially also do it just inside of the algo, if we don't want to translate the patterns up-front for pretty-printing purposes)

I think it would create more confusion. Right now, we can tell to users that (accessible) patterns are instructing Lean to perform case-analysis. This would not be true anymore with this change. I also don't see a clear benefit.

**Comment by DanielFabian** [comment] 2021-05-22 18:06
Fair enough. We can close it, then

**Closed** 2021-05-22 18:51 UTC
