### ISSUE TITLE
Termination checking doesn't work for *tactics* on indexed inductive types

### ISSUE THREAD

**Issue by imbrem** [leanprover/lean4#848] opened 2021-12-03 20:52 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

For some reason, simple termination checking doesn't seem to work for *indexed* inductive types when tactics are used, though it works for non-indexed types.

### Steps to Reproduce

Both the following programs type-check:
```lean
inductive Tree: Type
  | leaf: Nat-> Tree
  | node: Tree -> Tree -> Tree

def Tree.sum: Tree -> Nat
  | Tree.leaf n => n
  | Tree.node l r => sum l + sum r

def Tree.mul (m: Nat): Tree -> Tree
  | Tree.leaf n => Tree.leaf (n * m)
  | Tree.node l r => Tree.node (mul m l) (mul m r)

def sumRec (m: Nat): (T: Tree) -> Tree.sum (Tree.mul m T) = Tree.sum T * m
  | Tree.leaf n => rfl
  | Tree.node l r => by {
    simp only [Tree.sum, Tree.mul];
    simp only [sumRec];
    rw[Nat.add_mul]
  }

def sumRecTac (m: Nat) (T: Tree):  Tree.sum (Tree.mul m T) = Tree.sum T * m := by {
  cases T with
  | leaf n => rfl
  | node l r =>
    simp only [Tree.sum, Tree.mul];
    simp only [sumRec];
    rw[Nat.add_mul]
}
```
```lean
inductive BalTree: Nat -> Type
  | leaf: Nat -> BalTree 0
  | node: BalTree n -> BalTree n -> BalTree (n + 1)

def BalTree.sum: BalTree m -> Nat
  | BalTree.leaf n => n
  | BalTree.node l r => sum l + sum r

def BalTree.mul (m: Nat): BalTree i -> BalTree i
  | BalTree.leaf n => BalTree.leaf (n * m)
  | BalTree.node l r => BalTree.node (mul m l) (mul m r)

def balSumRec (m: Nat): (T: BalTree i) -> BalTree.sum (BalTree.mul m T) = BalTree.sum T * m
  | BalTree.leaf n => rfl
  | BalTree.node l r => by {
    simp [BalTree.sum, BalTree.mul];
    simp only [balSumRec];
    rw[Nat.add_mul]
  }
```
However, when I try to perform a proof by cases in tactic mode recursively, as follows
```lean
def balSumRecTac (m: Nat) (T: BalTree i): BalTree.sum (BalTree.mul m T) = BalTree.sum T * m := by {
  cases T with
  | leaf n => rfl
  | node l r =>
    simp [BalTree.sum, BalTree.mul];
    simp only [balSumRecTac];
    rw[Nat.add_mul]
}
```
I get the following error
```
fail to show termination for
  balSumRecTac
with errors
argument #2 was not used for structural recursion
  failed to eliminate recursive application
    balSumRecTac m l

argument #3 was not used for structural recursion
  failed to eliminate recursive application
    balSumRecTac m l

argument #1 was not used for structural recursion
  failed to eliminate recursive application
    balSumRecTac m l

structural recursion cannot be used

'termination_by' modifier missing
```

**Expected behavior:** termination check passes

**Actual behavior:** termination check fails

**Reproduces how often:** every time

### Versions

Lean (version 4.0.0-nightly-2021-12-03, commit c7565c446aa7, Release) on Ubuntu 20.04

**Comment by leodemoura** [comment] 2021-12-03 21:56
Structural recursion in Lean is based on the automatically generated auxiliary construction `brecOn`. You can see the actual term sent to the kernel by using the `#print` command. Example:
```lean
#print balSumRec
#print balSumRec.proof_1
```
The `brecOn` construction provides the "below" argument that is used to eliminate the recursive applications. This argument is "refined" through `match` expressions, but not through `casesOn` applications generated by the `cases` tactic. Note that you can use `match` in tactic mode and write.
```lean
def balSumRecTac (m: Nat) (T: BalTree i): BalTree.sum (BalTree.mul m T) = BalTree.sum T * m := by {
  match T with
  | BalTree.leaf n => rfl
  | BalTree.node l r =>
    simp [BalTree.sum, BalTree.mul];
    simp only [balSumRecTac]
    rw[Nat.add_mul]
}
```
You can also use the `induction` tactic
```lean
def balSumRecTac' (m: Nat) (T: BalTree i): BalTree.sum (BalTree.mul m T) = BalTree.sum T * m := by {
  induction T with
  | leaf n => rfl
  | node l r ih1 ih2 =>
    simp [BalTree.sum, BalTree.mul];
    simp only [ih1, ih2]
    rw[Nat.add_mul]
}
```
In principle, we could add support for `casesOn` applications to the structural recursion module, but we have no plans for doing it since users can use the `match` tactic.

**Comment by leodemoura** [comment] 2021-12-03 21:58
Remark: note that the issue is not related to indexed families. The example `sumRecTac` worked because it is not recursive. You used `simp only [sumRec]`.

**Comment by imbrem** [comment] 2021-12-04 01:12
@leodemoura my bad, that was a typo! The reason why I want support for `casesOn` applications is because I want to be able to support programs like the following:
```lean
def sumRecTac (m: Nat) (T: Tree):  Tree.sum (Tree.mul m T) = Tree.sum T * m := by {
  cases T;
  repeat {
    try rfl;
    try {
      simp only [Tree.sum, Tree.mul];
      simp only [sumRecTac];
      rw[Nat.add_mul]
    }
  }
}
```
While in this case this isn't particularly simpler, I have to do a lot of proofs with extremely repetitive cases for lots (around 30!) of constructors, and it's getting really annoying haha. Afaik I can't do that with match.

**Comment by leodemoura** [comment] 2021-12-04 01:20
> While in this case this isn't particularly simpler, I have to do a lot of proofs with extremely repetitive cases for lots (around 30!) of constructors

What about using `induction` instead? The induction hypotheses will be in the context, and you can instruct `simp` to use them. Example:
```lean
def sumRecTac (m: Nat) (T: Tree):  Tree.sum (Tree.mul m T) = Tree.sum T * m := by {
  induction T;
  repeat {
    try rfl;
    try {
      simp only [*, Tree.sum, Tree.mul]; -- The `*` is instructing Lean to use all equations in the local context which includes the induction hypotheses introduced by `induction`
      rw[Nat.add_mul]
    }
  }
}
```

**Comment by imbrem** [comment] 2021-12-04 02:36
The inductive hypotheses generated, unfortunately, were a bit of a pain to use. Would it be possible to write a tactic that just generates what is essentially a match statement with each branch being the same tactic? That's basically all I need here (and what my current code is!)

**Comment by leodemoura** [comment] 2022-03-02 18:36
I am closing this issue since there isn't any bug to be fixed here.

**Closed by leodemoura** 2022-03-02 18:36 UTC
