### ISSUE TITLE
LSP: Redundant error messages

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lean4#939] opened 2022-01-11 01:13 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean4/issues).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

Sometimes I get very redundant messages like this:

![image](https://user-images.githubusercontent.com/18707114/148863899-a7e76218-dfab-4948-a016-be7a2b43b3ce.png)

### Steps to Reproduce

open List
theorem nil_is_empty (x : List α) : (nil = []) := rfl

**Expected behavior:** 

should weed out redundant messages

**Actual behavior:**

no weeding

**Reproduces how often:** 

100%

### Versions

"leanprover/lean4:nightly-2022-01-05"

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by leodemoura** [comment] 2022-01-11 01:28
I did not manage to reproduce the error. The error message for a file containing
```lean
theorem nil_is_empty (x : List α) : (nil = []) := rfl
```
produces the error message
```
939.lean:1:37: error: unknown identifier 'nil'
```
Could you please double-check the example at "Steps to Reproduce"?

**Comment by lovettchris** [comment] 2022-01-11 01:35
sorry  missed "open List" and added it to the repro

**Comment by leodemoura** [comment] 2022-01-11 01:41
The error messages are not redundant. Note that there are not identical. The error messages are for implicit arguments that could not be synthesized. One for `nil`, one for `[]` (the other `nil`), and one for the equality application.

**Comment by leodemoura** [comment] 2022-01-17 16:52
I am closing this issue since the error messages are not redundant.

**Closed by leodemoura** 2022-01-17 16:52 UTC
